var AtingeAnalytics;
(function(d){function k(){var a=""+Math.random()+(new Date).getTime()+window.location.href;return e(a,0).toString(16)+e(a,2588935699).toString(16)}function e(a,f){var n,d,b,c,e;n=a.length&3;d=a.length-n;b=f;for(e=0;e<d;)c=a.charCodeAt(e)&255|(a.charCodeAt(++e)&255)<<8|(a.charCodeAt(++e)&255)<<16|(a.charCodeAt(++e)&255)<<24,++e,c=3432918353*(c&65535)+((3432918353*(c>>>16)&65535)<<16)&4294967295,c=c<<15|c>>>17,c=461845907*(c&65535)+((461845907*(c>>>16)&65535)<<16)&4294967295,b^=c,b=b<<13|b>>>19,b=5*
(b&65535)+((5*(b>>>16)&65535)<<16)&4294967295,b=(b&65535)+27492+(((b>>>16)+58964&65535)<<16);c=0;switch(n){case 3:c^=(a.charCodeAt(e+2)&255)<<16;case 2:c^=(a.charCodeAt(e+1)&255)<<8;case 1:c^=a.charCodeAt(e)&255,c=3432918353*(c&65535)+((3432918353*(c>>>16)&65535)<<16)&4294967295,c=c<<15|c>>>17,b^=461845907*(c&65535)+((461845907*(c>>>16)&65535)<<16)&4294967295}b^=a.length;b^=b>>>16;b=2246822507*(b&65535)+((2246822507*(b>>>16)&65535)<<16)&4294967295;b^=b>>>13;b=3266489909*(b&65535)+((3266489909*(b>>>
16)&65535)<<16)&4294967295;return(b^b>>>16)>>>0}function c(a,f,b){b=b||{cookies:!0,storage:!0,persist:!0};a=d.config.dataPrefix+a;if(b.storage){if(b.persist&&window.localStorage){localStorage.setItem(a,f);return}if(window.sessionStorage){sessionStorage.setItem(a,f);return}}b.cookies&&(document.cookie=a+"="+encodeURIComponent(f))}function b(a){var f;a=d.config.dataPrefix+a;if(window.localStorage&&(f=window.localStorage.getItem(a))||window.sessionStorage&&(f=window.sessionStorage.getItem(a)))return f;
a+="=";f=document.cookie.split(";");for(var b=0;b<f.length;b++){for(var c=f[b];" "==c.charAt(0);)c=c.substring(1,c.length);if(0==c.indexOf(a))return c.substring(a.length,c.length)}return null}d.client=function(){var a=window.atingePublisher,f=typeof a;if("function"===f)return a;var b=function(){return b.cmd.push(arguments)};b.cmd="undefined"!==f&&a.length?a:[];b.push=b;return window.atingePublisher=b}();d.config={"publisherId":"Dx5CcmXNwd6mFu","baseUrl":"//e.cdn-hardware.com.br/","logFirstDelay":50,"logDelay":2000,"dataPrefix":"atinge_","naveggAsync":true,"extensive":true,"beacon":false};d.getStrongRandom=k;d.getIdString=function(){return Math.floor(4294967295*
Math.random()).toString(16)};d.murmurhash3_32_gc=e;d.setData=c;d.getData=b;d.getUid=function(){var a=b("uid");if(a)return a;a=k().substr(0,14);c("uid",a);return a}})(AtingeAnalytics||(AtingeAnalytics={}));
(function(d){d.domReady=function(d){var e=!1,c=!0,b=window,a=b.document,f=a.documentElement,n=a.addEventListener,h=n?"addEventListener":"attachEvent",g=n?"removeEventListener":"detachEvent",l=n?"":"on",m=function(f){if(!("readystatechange"==f.type&&"complete"!=a.readyState)&&(("load"==f.type?b:a)[g](l+f.type,m,!1),!e&&(e=!0)))d.call(b,f.type||f)},p=function(){try{f.doScroll("left")}catch(a){setTimeout(p,50);return}m("poll")};if("complete"==a.readyState)d.call(b,"lazy");else{if(!n&&f.doScroll){try{c=
!b.frameElement}catch(r){}c&&p()}a[h](l+"DOMContentLoaded",m,!1);a[h](l+"readystatechange",m,!1);b[h](l+"load",m,!1)}};d.debounce=function(d,e,c){var b;return function(){var a=this,f=arguments,n=c&&!b;clearTimeout(b);b=setTimeout(function(){b=null;c||d.apply(a,f)},e);n&&d.apply(a,f)}};d.each=function(d,e){for(var c in d)d.hasOwnProperty(c)&&e(d[c],c)};d.$script=function(){function d(a,f){for(var b=0,c=a.length;b<c;++b)if(!f(a[b]))return n;return 1}function e(a,f){d(a,function(a){return!f(a)})}function c(a,
f,n){function g(a){return a.call?a():m[a]}function l(){if(!--v){m[w]=1;q&&q();for(var a in p)d(a.split("|"),g)&&!e(p[a],g)&&(p[a]=[])}}a=a[h]?a:[a];var t=f&&f.call,q=t?f:n,w=t?a.join(""):f,v=a.length;setTimeout(function(){e(a,function x(a,f){if(null===a)return l();a=!f&&-1===a.indexOf(".js")&&!/^https?:\/\//.test(a)&&s?s+a+".js":a;if(r[a])return 2==r[a]?l():setTimeout(function(){x(a,!0)},0);r[a]=1;b(a,l)})},0);return c}function b(b,d){var c=a.createElement("script"),n;c.onload=c.onerror=c[l]=function(){c[g]&&
!/^c|loade/.test(c[g])||n||(c.onload=c[l]=null,n=1,r[b]=2,d())};c.async=1;c.src=q?b+(-1===b.indexOf("?")?"?":"&")+q:b;f.insertBefore(c,f.lastChild)}var a=document,f=a.getElementsByTagName("head")[0],n=!1,h="push",g="readyState",l="onreadystatechange",m={},p={},r={},s,q;c.get=b;c.order=function(a,f,b){(function u(d){d=a.shift();!a.length?c(d,f,b):c(d,u)})()};c.path=function(a){s=a};c.urlArgs=function(a){q=a};c.ready=function(a,f,b){a=a[h]?a:[a];var n=[];!e(a,function(a){m[a]||n[h](a)})&&d(a,function(a){return m[a]})?
f():!function(a){p[a]=p[a]||[];p[a][h](f);b&&b(n)}(a.join("|"));return c};c.done=function(a){c([null],a)};return c}();d.addEvent=function(d,e,c){d.attachEvent?d.attachEvent("on"+e,c):d.addEventListener&&d.addEventListener(e,c,!1)};d.removeEvent=function(d,e,c){d.detachEvent?d.detachEvent("on"+e,c):d.removeEventListener&&d.removeEventListener(e,c,!1)};String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,"")});Array.prototype.indexOf||(Array.prototype.indexOf=
function(d,e){var c,b,a;c=Object(this);b=c.length>>>0;void 0!==e?(e=toInteger(e),a=0>e?Math.max(b+e,0):Math.min(e,b)):a=0;for(;a<b;++a)if(a in c&&d===c[a])return a;return-1});Function.prototype.bind||(Function.prototype.bind=function(d){var e=Array.prototype.slice.call(arguments,1),c=this,b=function(){},a=function(){return c.apply(this instanceof b?this:d,e.concat(Array.prototype.slice.call(arguments)))};this.prototype&&(b.prototype=this.prototype);a.prototype=new b;return a})})(AtingeAnalytics);
(function(d){function k(b){if(!b.length)return b;for(var a=0;a<b.length;a++){var f=b[a];try{f()}catch(d){console.log(d.stack||d)}}return[]}function e(){for(var b=navigator.plugins,a="",f=0;f<b.length;++f){var c=b[f];"string"==typeof c.name&&(a+=c.name);"string"==typeof c.description&&(a=a+"/"+c.description);"string"==typeof c.filename&&(a=a+"/"+c.filename);a+="\n"}return d.murmurhash3_32_gc(a,0).toString(16)+d.murmurhash3_32_gc(a,2588935699).toString(16)+d.murmurhash3_32_gc(a,3237188224).toString(16)}
var c=function(){function b(){var a=this;this.baseUrl=d.config.baseUrl;this.firstRequest=!0;this.pageviewCalled=!1;this.beforeFlush=[];this.afterFlush=[];this.unloadFlush=function(){a.immediateFlush(!0)};d.client.base=this.base.bind(this);d.client.targeting=this.targeting.bind(this);d.client.slot=this.slot.bind(this);d.client.pageview=this.pageview.bind(this)}b.prototype.newRequest=function(){var a=this,f=this.request;if(f)return this.debounceFlush&&this.debounceFlush(),f;d.addEvent(window,"pagehide",
this.unloadFlush);d.addEvent(window,"unload",this.unloadFlush);d.addEvent(window,"beforeunload",this.unloadFlush);var f=new d.Request.Beacon,b=function(f){a.debounceFlush=d.debounce(a.immediateFlush.bind(a),f);a.debounceFlush()};this.firstRequest?d.domReady(function(){b(d.config.logFirstDelay||0)}):b(d.config.logDelay||0);return this.request=f};b.prototype.immediateFlush=function(a){var f=this.request;if(f&&(!this.firstRequest||this.pageviewCalled)){this.beforeFlush=k(this.beforeFlush);this.request=
void 0;this.firstRequest=!1;this.debounceFlush=null;d.removeEvent(window,"pagehide",this.unloadFlush);d.removeEvent(window,"unload",this.unloadFlush);d.removeEvent(window,"beforeunload",this.unloadFlush);this.pageviewCalled&&(this.newPageview(f),this.pageviewCalled=!1);f.add("id",d.config.publisherId).add("u",d.getUid()).add("bi",this.pageviewId);var b=this.baseUrl+"b",c=this.afterFlush;a={unload:a};c.length&&(this.afterFlush=[],a.callback=function(){k(c)});f.send(b,a)}};b.prototype.base=function(a){this.baseUrl=
a};b.prototype.targeting=function(a){for(var f=[],b=1;b<arguments.length;b++)f[b-1]=arguments[b];for(var f=d.flatten(f),b=this.newRequest().map("tg"),c=0;c<f.length;c++)b.add(a,f[c])};b.prototype.slot=function(a){for(var b=[],c=1;c<arguments.length;c++)b[c-1]=arguments[c];b=d.flatten(b);if(b.length)for(var c=this.newRequest().map("slt"),e=0;e<b.length;e++)c.add(a,b[e]);else this.newRequest().array("slta").push(a)};b.prototype.pageview=function(){this.newRequest();this.pageviewCalled=!0};b.prototype.newPageview=
function(a){this.pageviewId=d.getStrongRandom().substr(0,12);var b=0;window.localStorage&&(b|=1);window.sessionStorage&&(b|=2);window.orientation&&(b|=4);var c;try{c=window.self!==window.top}catch(h){c=!0}c&&(b|=8);c=new Date;a.add("ft",b).add("ph",e()).add("sww",screen.width).add("swh",screen.height).add("sc",screen.colorDepth).add("sx",void 0===window.screenLeft?window.screenX:window.screenLeft).add("sy",void 0===window.screenTop?window.screenY:window.screenTop).add("t",c.getTime()).add("tz",c.getTimezoneOffset());
d.config.extensive&&a.add("tl",document.title).add("rf",document.referrer)};return b}();d.logger=new c})(AtingeAnalytics||(AtingeAnalytics={}));
(function(d){function k(a){for(var b=[],c=0;c<arguments.length;c++){var d=arguments[c],e=typeof d;"undefined"!==e&&"string"!==e&&null!==d&&"number"===typeof d.length?b.push.apply(b,k.apply(this,d)):b.push(d)}return b}function e(a){if(!(null===a||"undefined"===typeof a||"number"===typeof a&&isNaN(a)))return a=a.toString().trim(),a.length?a:void 0}function c(a,b){if(b&&b.length){for(var c="",d=0;d<b.length;d++){var g;g=a;var l=e(b[d]);if(!l||0>l.indexOf(g))g=l;else{for(var m="",p=0;p<l.length;++p){var k=
l.charAt(p);k===g&&(m+=g);m+=k}g=m}g&&(""!==c&&(c+=a),c+=g)}return c.length?c:void 0}}d.flatten=k;d.stringify=e;d.stringifyArray=function(a){return c("~",a)};var b=function(){function a(){this.map={}}a.prototype.add=function(a,b){a=e(a);b=e(b);if(!a||!b)return!1;var c=this.map[a];c?0>c.indexOf(b)&&c.push(b):this.map[a]=[b]};a.prototype.stringify=function(){var a=[];d.each(this.map,function(b,d){a.push(d);a.push(c("_",b))});return c("~",a)};return a}();d.Multimap=b})(AtingeAnalytics||(AtingeAnalytics=
{}));
(function(d){(function(k){var e={};k.Callback=function(b){var a=e[b];a&&(delete e[b],a())};var c=function(){function b(){this.items=[];this.maps={};this.arrays={}}b.prototype.add=function(a,b){(b=d.stringify(b))&&this.items.push({name:a,value:b});return this};b.prototype.map=function(a){var b=this.maps[a];return b?b:this.maps[a]=new d.Multimap};b.prototype.array=function(a){var b=this.arrays[a];return b?b:this.arrays[a]=[]};b.prototype.send=function(a,b){var c;if(b.callback){for(var h=void 0,g=0;;){h=
g.toString();if(!e[h])break;g++}e[h]=b.callback;a+="/"+h}var l=this.items.slice();d.each(this.maps,function(a,b){var c=a.stringify();c&&l.push({name:b,value:c})});d.each(this.arrays,function(a,b){var c=d.stringifyArray(a);c&&l.push({name:b,value:c})});l.push({name:"r",value:d.getIdString().substr(0,4)});for(h=0;h<l.length;h++)g=l[h],g=encodeURIComponent(g.name)+"="+encodeURIComponent(g.value),c=c?c+"&"+g:g;c=a+"?"+c;h=navigator;g=d.config.beacon?h.sendBeacon&&(b.unload||!b.callback):h.sendBeacon&&
b.unload;try{if(g&&h.sendBeacon(c))return}catch(m){}d.$script(c)};return b}();k.Beacon=c})(d.Request||(d.Request={}))})(AtingeAnalytics||(AtingeAnalytics={}));
(function(d){(function(k){function e(){var c=window.googletag=window.googletag||{};c.cmd=c.cmd||[];return c}k.getGoogleTag=e;new (function(){function c(){var b=this,a=e();a.cmd.push(function(){var c=a.debug_log;if(c){var d=c.getAllEvents();if(d)for(var e=0;e<d.length;e++){var g=d[e];b.processEvent(g.getMessage(),g.getSlot())}var l=c.log;c.log=function(a,c,d,f,e){c&&(c.getMessageId&&"number"==typeof c.getMessageId())&&b.processEvent(c,f);return l.apply(this,arguments)}}})}c.prototype.processEvent=
function(b,a){var c=b.getMessageId();if(3==c){if(c=a.getSlotId().getName()){var c=["slot",c],e=a.getSizes();if(e)for(var h=0;h<e.length;h++){var g=e[h],l=g.getHeight(),g=g.getWidth();l&&g&&c.push(g+"x"+l)}d.client(c)}}else 88==c&&(e=b.getMessageArgs(),3==e.length&&"publisher_ads"===e[2]&&(c=e[1].split(","),c.unshift("targeting",e[0]),d.client(c)))};return c}())})(d.DFP||(d.DFP={}))})(AtingeAnalytics||(AtingeAnalytics={}));
(function(d){(function(k){new (function(){function e(){d.config.naveggAsync&&this.enable()}e.prototype.signature=function(){return Math.round((new Date).getTime()/216E5).toString(16)};e.prototype.enable=function(){var c=this,b=d.getData("navegg_usr"),a=d.getData("navegg_ids"),f=d.getData("navegg_values"),e=this.signature(),h=a&&f;h&&this.setTargeting(a,f);e!==d.getData("navegg_logged")?(b=function(){},window.nvg33590={start:function(a,b,f){if(!b||"string"!==typeof b||!f||"string"!==typeof f)f=b="";
b?(h||c.setTargeting(b,f),d.logger.afterFlush.push(function(){d.setData("navegg_logged",e)})):d.setData("navegg_logged",e);var k={storage:!0,persist:!0,cookies:!1};d.setData("navegg_ids",b,k);d.setData("navegg_values",f,k);c.log("33590",a)},include:b,doSync:b},d.$script("//usr.navdmp.com/usr?v=7&acc=33590&new=1&wst=0")):b&&this.log("33590",b)};e.prototype.log=function(c,b){d.$script("//cdn.navdmp.com/req?v=7&upd=1&acc="+c+"&id="+b+"&tit="+escape(window.document.title))};e.prototype.setTargeting=function(c,
b){if(b){for(var a=c.split(":"),f=b.split(":"),e=Math.min(a.length,f.length),h=[],g=0;g<e;++g){var l=a[g],m=f[g].trim();""!=m&&(m=m.split("-"),h.push({id:l,values:m}),m=m.slice(),m.unshift("targeting",l),d.client(m))}var k=d.DFP.getGoogleTag();k.cmd.push(function(){for(var a=0;a<h.length;a++){var b=h[a];k.pubads().setTargeting(b.id,b.values)}})}};return e}())})(d.Navegg||(d.Navegg={}))})(AtingeAnalytics||(AtingeAnalytics={}));
(function(d){function k(){if(document.querySelectorAll)for(var e=document.querySelectorAll(".adsbygoogle"),c=0;c<e.length;++c){var b=e.item?e.item(c):e[c],a=Math.floor(b.clientWidth),f=Math.floor(b.clientHeight),k=b.getAttribute("data-ad-slot"),h=b.getAttribute("data-adsbygoogle-status");if(a&&f&&k&&h){a=a+"x"+f;if(f=b.getAttribute("data-ad-format")){b=0;for(f=f.split(",");b<f.length;b++)h=f[b].substr(0,1),0<=["a","r","v","h"].indexOf(h)&&(a+=h)}d.logger.newRequest().map("sads").add(k,a)}}}d.config.skipAutoAdsense||
d.client(function(){d.logger.beforeFlush.push(k)})})(AtingeAnalytics||(AtingeAnalytics={}));
(function(d){var k=function(){function e(c){if(c.length)for(var b=0;b<c.length;b++){var a=c[b];try{this.push.apply(this,Array.prototype.slice.call(a))}catch(d){console.log(d.stack||d)}}this.push=this.push.bind(this)}e.prototype.push=function(c){for(var b=[],a=1;a<arguments.length;a++)b[a-1]=arguments[a];for(a=2;a--;){var e=typeof c;if("function"===e){c(d.client);return}if("string"!==e&&0===b.length&&c.length)b=Array.prototype.slice.call(c),c=b.shift();else break}return d.client[c].apply(d.client,
b)};return e}();d.ForwardCommands=k;d.client.started||(d.client.cmd=new k(d.client.cmd),d.client.started=!0)})(AtingeAnalytics||(AtingeAnalytics={}));
