(function(g){var window=this;var cBa=function(a,b){return g.Ub(a,b)},S6=function(a){g.Em(a,"zx",g.yb());
return a},T6=function(a,b,c){g.Aa(c)||(c=[String(c)]);
g.Hm(a.g,b,c)},dBa=function(a,b){var c=[];
g.qk(b,function(a){try{var b=g.eD.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.dD(b)&&c.push(a):c.push(a)},a);
return c},eBa=function(a,b){var c=dBa(a,b);
(0,g.B)(c,function(a){g.eD.prototype.remove.call(this,a)},a)},fBa=function(a){if(a.zd){if(a.zd.locationOverrideToken)return{locationOverrideToken:a.zd.locationOverrideToken};
if(null!=a.zd.latitudeE7&&null!=a.zd.longitudeE7)return{latitudeE7:a.zd.latitudeE7,longitudeE7:a.zd.longitudeE7}}return null},gBa=function(a,b,c,d){var e=new g.vm(null,void 0);
a&&g.wm(e,a);b&&g.xm(e,b);c&&g.ym(e,c);d&&g.zm(e,d);return e},hBa=function(a){g.UF[a]&&(a=g.UF[a],(0,g.B)(a,function(a){g.SF[a]&&delete g.SF[a]}),a.length=0)},iBa=function(a){var b=g.RF();
if(b)if(b.clear(a),a)hBa(a);else for(var c in g.UF)hBa(c)},U6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.pm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",jBa(this,a.capabilities||""),kBa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},jBa=function(a,b){a.capabilities.clear();
(0,g.Kd)(b.split(","),g.Ga(cBa,lBa)).forEach(function(b){a.capabilities.add(b)})},kBa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},V6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},W6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},mBa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},nBa=function(a){return new V6(a)},oBa=function(a){return g.Aa(a)?(0,g.G)(a,nBa):[]},X6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},Y6=function(a){return g.Aa(a)?"["+(0,g.G)(a,X6).join(",")+"]":"null"},Z6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},pBa=function(a){return(0,g.G)(a,function(a){return{key:a.id,
name:a.name}})},$6=function(a,b){return g.La(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},a7=function(a,b){return g.La(a,function(a){return W6(a,b)})},qBa=function(){var a=(0,g.OG)();
a&&eBa(a,a.g.Vd(!0))},b7=function(){var a=g.RG("yt-remote-connected-devices")||[];
g.gb(a);return a},rBa=function(a){if(g.Qa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(a,b){return 0==b?a:a.substring(c.length)})},sBa=function(a){g.QG("yt-remote-connected-devices",a,86400)},d7=function(){if(c7)return c7;
var a=g.RG("yt-remote-device-id");a||(a=Z6(),g.QG("yt-remote-device-id",a,31536E3));for(var b=b7(),c=1,d=a;g.Pa(b,d);)c++,d=a+"#"+c;return c7=d},e7=function(){var a=b7(),b=d7();
g.Pa(a,b);g.TG()&&g.jb(a,b);a=rBa(a);if(g.Qa(a))try{g.AG("remote_sid")}catch(c){}else try{g.zG("remote_sid",a.join(","),-1)}catch(c){}},tBa=function(){return g.RG("yt-remote-session-browser-channel")},uBa=function(){return g.RG("yt-remote-local-screens")||[]},vBa=function(){g.QG("yt-remote-lounge-token-expiration",!0,86400)},wBa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(uBa(),function(a){return a.loungeToken}),c=(0,g.G)(a,function(a){return a.loungeToken});
(0,g.dm)(c,function(a){return!g.Pa(b,a)})&&vBa();
g.QG("yt-remote-local-screens",a,31536E3)},xBa=function(a,b){g.QG("yt-remote-session-browser-channel",a);
g.QG("yt-remote-session-screen-id",b);var c=b7(),d=d7();g.Pa(c,d)||c.push(d);sBa(c);e7()},f7=function(a){a||(g.SG("yt-remote-session-screen-id"),g.SG("yt-remote-session-video-id"));
e7();a=b7();g.Ua(a,d7());sBa(a)},yBa=function(){if(!g7){var a=g.pD();
a&&(g7=new g.ZC(a))}return g7?!!g7.get("yt-remote-use-staging-server"):!1},zBa=function(){var a=window.document.createElement("a");
g.$c(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Cb(a)},ABa=function(a,b){var c=g.Dd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.ad(c,g.be("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},BBa=function(){var a=zBa(),b=window.document.getElementById(a),c=b&&g.cF(b,"loaded");
c||b&&!c||(b=ABa(a,function(){g.cF(b,"loaded")||(g.bF(b,"loaded","true"),g.YF(a),g.YD(g.Ga(iBa,a),0))}))},h7=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},CBa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},i7=function(a){a.length?DBa(a.shift(),function(){i7(a)}):j7()},EBa=function(a){return"chrome-extension://"+a+k7},DBa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},l7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},j7=function(){var a=CBa();
a&&a(!1,"No cast extension found")},m7=function(){if(FBa){var a=2,b=CBa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;DBa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",j7,c)}},GBa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(m7(),a({command:"cast.sender.init"}))},HBa=function(){m7();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);i7(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+k7,"//www.gstatic.com/eureka/clank"+k7])},n7=function(a,b,c){g.M.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.qd=b;this.B=(0,g.z)(this.UJ,this);this.g=!1;this.l=0;this.o=this.Ca=null;this.A=[]},o7=function(){},p7=function(a,b,c,d){this.g=a;
this.o=b;this.D=c;this.C=d||1;this.A=45E3;this.W=new g.Lm(this);this.l=new g.rg;this.l.setInterval(250)},JBa=function(a,b,c){a.Lj=1;
a.mh=S6(b.clone());a.Si=c;a.B=!0;IBa(a,null)},q7=function(a,b,c,d,e){a.Lj=1;
a.mh=S6(b.clone());a.Si=null;a.B=c;e&&(a.lE=!1);IBa(a,d)},IBa=function(a,b){a.Ck=(0,g.F)();
r7(a);a.Jh=a.mh.clone();T6(a.Jh,"t",a.C);a.Tm=0;a.Qc=a.g.Rr(a.g.Jm()?b:null);0<a.Gs&&(a.Pp=new g.Uk((0,g.z)(a.DF,a,a.Qc),a.Gs));a.W.U(a.Qc,"readystatechange",a.tV);var c=a.ni?g.bc(a.ni):{};a.Si?(a.Dq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Qc.send(a.Jh,a.Dq,a.Si,c)):(a.Dq="GET",a.lE&&!g.zd&&(c.Connection="close"),a.Qc.send(a.Jh,a.Dq,null,c));a.g.yf(1)},MBa=function(a,b,c){for(var d=!0;!a.Xh&&a.Tm<c.length;){var e=KBa(a,c);
if(e==s7){4==b&&(a.nh=4,t7(15),d=!1);break}else if(e==LBa){a.nh=4;t7(16);d=!1;break}else u7(a,e)}4==b&&0==c.length&&(a.nh=1,t7(17),d=!1);a.Ef=a.Ef&&d;d||(v7(a),w7(a))},KBa=function(a,b){var c=a.Tm,d=b.indexOf("\n",c);
if(-1==d)return s7;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return LBa;d+=1;if(d+c>b.length)return s7;var e=b.substr(d,c);a.Tm=d+c;return e},OBa=function(a,b){a.Ck=(0,g.F)();
r7(a);var c=b?window.location.hostname:"";a.Jh=a.mh.clone();g.Em(a.Jh,"DOMAIN",c);g.Em(a.Jh,"t",a.C);try{a.Ff=new window.ActiveXObject("htmlfile")}catch(n){v7(a);a.nh=7;t7(22);w7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in x7)k=x7[l];else if(l in NBa)k=x7[l]=NBa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=x7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.bd(g.xc("b/12014412"),d);a.Ff.open();a.Ff.write(g.Uc(c));a.Ff.close();a.Ff.parentWindow.m=(0,g.z)(a.CU,a);a.Ff.parentWindow.d=(0,g.z)(a.uD,a,!0);a.Ff.parentWindow.rpcClose=(0,g.z)(a.uD,a,!1);c=a.Ff.createElement("DIV");a.Ff.parentWindow.document.body.appendChild(c);d=g.Lc(a.Jh.toString());d=g.qb(g.Ic(d));d=g.bd(g.xc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Uc(d);
a.g.yf(1)},r7=function(a){a.jw=(0,g.F)()+a.A;
PBa(a,a.A)},PBa=function(a,b){if(null!=a.Sk)throw Error("WatchDog timer not null");
a.Sk=y7((0,g.z)(a.SU,a),b)},z7=function(a){a.Sk&&(g.w.clearTimeout(a.Sk),a.Sk=null)},w7=function(a){a.g.Cz()||a.Xh||a.g.Bp(a)},v7=function(a){z7(a);
g.Ze(a.Pp);a.Pp=null;a.l.stop();g.Rm(a.W);if(a.Qc){var b=a.Qc;a.Qc=null;b.abort();b.dispose()}a.Ff&&(a.Ff=null)},u7=function(a,b){try{a.g.nD(a,b),a.g.yf(4)}catch(c){}},RBa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;QBa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){RBa(a,b,c,d,f)},f)})}},QBa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{A7(d),c(!0)}catch(e){}};
d.onerror=function(){try{A7(d),c(!1)}catch(e){}};
d.onabort=function(){try{A7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{A7(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},A7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},SBa=function(a){this.g=a;
this.l=new o7},TBa=function(a){var b=B7(a.g,a.dl,"/mail/images/cleardot.gif");
S6(b);RBa(b.toString(),5E3,(0,g.z)(a.gJ,a),3,2E3);a.yf(1)},D7=function(a){var b=a.g.H;
if(null!=b)t7(5),b?(t7(11),C7(a.g,a,!1)):(t7(12),C7(a.g,a,!0));else if(a.we=new p7(a,void 0,void 0,void 0),a.we.ni=a.Es,b=a.g,b=B7(b,b.Jm()?a.Hl:null,a.Fs),t7(5),!g.xd||g.tc(10))T6(b,"TYPE","xmlhttp"),q7(a.we,b,!1,a.Hl,!1);else{T6(b,"TYPE","html");var c=a.we;a=!!a.Hl;c.Lj=3;c.mh=S6(b.clone());OBa(c,a)}},E7=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new o7;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},UBa=function(a,b){this.g=a;
this.map=b;this.context=null},VBa=function(a){g.af.call(this,"statevent",a)},WBa=function(a,b){g.af.call(this,"timingevent",a);
this.size=b},XBa=function(a){g.af.call(this,"serverreachability",a)},$Ba=function(a){YBa(a);
if(3==a.g){var b=a.rm++,c=a.lo.clone();g.Em(c,"SID",a.o);g.Em(c,"RID",b);g.Em(c,"TYPE","terminate");F7(a,c);b=new p7(a,a.o,b,void 0);b.Lj=2;b.mh=S6(c.clone());(new window.Image).src=b.mh;b.Ck=(0,g.F)();r7(b)}ZBa(a)},aCa=function(a){a.BJ(1,0);
a.lo=B7(a,null,a.Ds);G7(a)},YBa=function(a){a.ah&&(a.ah.abort(),a.ah=null);
a.tc&&(a.tc.cancel(),a.tc=null);a.sg&&(g.w.clearTimeout(a.sg),a.sg=null);H7(a);a.be&&(a.be.cancel(),a.be=null);a.eh&&(g.w.clearTimeout(a.eh),a.eh=null)},bCa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new UBa(a.lQ++,b));2!=a.g&&3!=a.g||G7(a)},G7=function(a){a.be||a.eh||(a.eh=y7((0,g.z)(a.sD,a),0),a.Aj=0)},dCa=function(a,b){if(1==a.g){if(!b){a.rm=Math.floor(1E5*Math.random());
var c=a.rm++,d=new p7(a,"",c,void 0);d.ni=null;var e=I7(a),f=a.lo.clone();g.Em(f,"RID",c);g.Em(f,"CVER","1");F7(a,f);JBa(d,f,e);a.be=d;a.g=2}}else 3==a.g&&(b?cCa(a,b):0==a.l.length||a.be||cCa(a))},cCa=function(a,b){if(b)if(6<a.Zh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.rm-1;var d=I7(a)}else c=b.D,d=b.Si;else c=a.rm++,d=I7(a);var e=a.lo.clone();g.Em(e,"SID",a.o);g.Em(e,"RID",c);g.Em(e,"AID",a.Zj);F7(a,e);c=new p7(a,a.o,c,a.Aj+1);c.ni=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.be=c;JBa(c,e,d)},F7=function(a,b){if(a.pd){var c=a.pd.hz();
c&&g.Kb(c,function(a,c){g.Em(b,c,a)})}},I7=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Zh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Zh?e:f-d;try{g.Kb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},eCa=function(a){a.tc||a.sg||(a.D=1,a.sg=y7((0,g.z)(a.rD,a),0),a.nj=0)},J7=function(a){if(a.tc||a.sg||3<=a.nj)return!1;
a.D++;a.sg=y7((0,g.z)(a.rD,a),fCa(a,a.nj));a.nj++;return!0},C7=function(a,b,c){a.Cq=c;
a.Uf=b.Dg;a.C||aCa(a)},H7=function(a){null!=a.ci&&(g.w.clearTimeout(a.ci),a.ci=null)},fCa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},K7=function(a,b){if(2==b||9==b){var c=null;
a.pd&&(c=null);var d=(0,g.z)(a.mW,a);c||(c=new g.vm("//www.google.com/images/cleardot.gif"),S6(c));QBa(c.toString(),1E4,d)}else t7(2);gCa(a,b)},gCa=function(a,b){a.g=0;
a.pd&&a.pd.Yx(b);ZBa(a);YBa(a)},ZBa=function(a){a.g=0;
a.Uf=-1;if(a.pd)if(0==a.A.length&&0==a.l.length)a.pd.Er();else{g.Xa(a.A);var b=g.Xa(a.l);a.A.length=0;a.l.length=0;a.pd.Er(b)}},B7=function(a,b,c){var d=g.Fm(c);
if(""!=d.l)b&&g.xm(d,b+"."+d.l),g.ym(d,d.B);else{var e=window.location;d=gBa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.tl&&g.Kb(a.tl,function(a,b){g.Em(d,b,a)});
g.Em(d,"VER",a.Zh);F7(a,d);return d},y7=function(a,b){if(!g.Ca(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},t7=function(a){L7.dispatchEvent(new VBa(L7,a))},hCa=function(){},iCa=function(a,b){this.action=a;
this.params=b||{}},M7=function(a,b){g.M.call(this);
this.g=new g.Xt(this.tU,0,this);g.N(this,this.g);this.qd=5E3;this.l=0;if(g.Ca(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Ca(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},N7=function(a,b,c){this.J=a;
this.C=b;this.o=new g.YC;this.l=new M7(this.WW,this);this.g=this.Ya=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.K=c||!1},jCa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Cq,sessionId:a.g.o,arrayId:a.g.Zj}},kCa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&dCa(a.g),$Ba(a.g));a.F=0},O7=function(a){return!!a.g&&3==a.g.g},lCa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},P7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Hg(a)||"";b&&(this.port=":"+b);this.domain=g.Gg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Bb(a,"10.0")&&(this.l=!1))},Q7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Qg(c+b,{})},R7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ga(a.A,d,!0),onError:g.Ga(a.o,e),wd:g.Ga(a.B,e)};c&&(a.Nb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.oE(b,a)},pCa=function(){var a=mCa;
nCa();S7.push(a);oCa(S7)},T7=function(a,b){nCa();
var c=S7,d=qCa(a,String(b));g.Qa(c)?rCa(d):(oCa(c),(0,g.B)(c,function(a){a(d)}))},nCa=function(){S7||(S7=g.x("yt.mdx.remote.debug.handlers_")||[],g.va("yt.mdx.remote.debug.handlers_",S7,void 0))},rCa=function(a){var b=(U7+1)%50;
U7=b;V7[b]=a;W7||(W7=49==b)},oCa=function(a){var b=V7;
if(b[0]){var c=U7,d=W7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(a){a(e)})}while(d!=c);
V7=Array(50);U7=-1;W7=!1}},qCa=function(a,b){var c=((0,g.F)()-sCa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},X7=function(a){g.JF.call(this);
this.D=a;this.g=[]},tCa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},uCa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Kd)(a.g,function(a){return!!$6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=tCa(a,b[d])||c;return c},vCa=function(a,b){var c=a.g.length;
a.g=(0,g.Kd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},Y7=function(a,b,c,d){g.JF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.Ca=window.NaN},$7=function(a){X7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;Z7(this);this.info("Initializing with "+Y6(this.g))},wCa=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(a){return a.id}),c=Q7(a.o,"/pairing/get_lounge_token_batch");
R7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.hK,a),(0,g.z)(a.gK,a))}},Z7=function(a){var b=oBa(uBa());
b=(0,g.Kd)(b,function(a){return!a.uuid});
return uCa(a,b)},a8=function(a,b){wBa((0,g.G)(a.g,mBa));
b&&vBa()},c8=function(a,b){g.JF.call(this);
this.C=b;var c=g.RG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Pa(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;b8("Initialized with "+g.yg(this.g))},xCa=function(a,b,c){var d=Q7(a.B,"/pairing/get_screen_availability");
R7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},d8=function(a,b){a:if(g.Ob(b)!=g.Ob(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(b8("Updated online screens: "+g.yg(a.g)),a.g=b,a.T("screenChange"));yCa(a)},e8=function(a){(0,window.isNaN)(a.o)||g.$D(a.o);
a.o=g.YD((0,g.z)(a.zv,a),0<a.A&&a.A<(0,g.F)()?2E4:1E4)},b8=function(a){T7("OnlineScreenService",a)},zCa=function(a){var b={};
(0,g.B)(a.C(),function(a){a.token?b[a.token]=a.id:this.fc("Requesting availability of screen w/o lounge token.")});
return b},yCa=function(a){a=g.Rb(g.Lb(a.g,function(a){return a}));
g.gb(a);a.length?g.QG("yt-remote-online-screen-ids",a.join(","),60):g.SG("yt-remote-online-screen-ids")},f8=function(a){X7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};ACa(this)},CCa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.oe();if(k=(c?a7(k,c):null)||a7(k,b)){k.uuid=b;var l=g8(a,k);xCa(a.l,l,function(a){e(a?l:null)})}else c?BCa(a,c,(0,g.z)(function(a){var f=g8(this,new V6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));xCa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},DCa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},BCa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Nb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.oE(Q7(a.C,"/pairing/get_lounge_token_batch"),e)},ECa=function(a){a.g=a.o.oe();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+Y6(a.g))},ACa=function(a){h8(a);
a.o=new $7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.wK,a));ECa(a);a.A=oBa(g.RG("yt-remote-automatic-screen-cache")||[]);h8(a);a.info("Initializing automatic screens: "+Y6(a.A));a.l=new c8(a.C,(0,g.z)(a.oe,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.T("onlineScreenChange")},a))},g8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=a7(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.QG("yt-remote-automatic-screen-cache",(0,g.G)(a.A,mBa)));h8(a);a.B[b.uuid]=b.id;g.QG("yt-remote-device-id-map",a.B,31536E3);return b},h8=function(a){a.B=g.RG("yt-remote-device-id-map")||{}},i8=function(a,b,c){g.JF.call(this);
this.K=c;this.H=a;this.l=b;this.o=null},j8=function(a,b){T7(a.K,b)},k8=function(a,b){i8.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.cX,this);this.B=(0,g.z)(this.eV,this);this.A=g.YD((0,g.z)(function(){FCa(this,null)},this),12E4)},GCa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.yg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){j8(this,"Failed to send message: getMdxSessionStatus.")},a)):j8(a,"Sending yt message without session: "+g.yg(b))},FCa=function(a,b){g.$D(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.Cp,a),d=(0,g.z)(a.te,a);a.rz(b,c,d,5)}}else a.te(Error("Waiting for session status timed out."))},l8=function(a,b,c){i8.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.M=c;this.B=null;this.D=g.y;this.C=window.NaN;this.J=(0,g.z)(this.fX,this);this.g=g.y},HCa=function(a){a.g=a.H.KF(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Cp(a)},a),(0,g.z)(function(a){this.g=g.y;
this.te(a)},a))},ICa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.M;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}yBa()&&(b.env_useStageMdx=1);return g.Og(b)},m8=function(a,b){i8.call(this,a,b,"ManualSession");
this.g=g.YD((0,g.z)(this.bk,this,null),150)},n8=function(a,b,c,d){g.JF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.BT,this)},JCa=function(a,b){return b?g.La(a.o,function(a){return W6(b,a.label)},a):null},o8=function(a){T7("Controller",a)},mCa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},p8=function(a){return a.B||!!a.o.length||!!a.g},q8=function(a,b,c){b!=a.g&&(g.Ze(a.g),(a.g=b)?(c?a.T("yt-remote-cast2-receiver-resumed",b.l):a.T("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.pD,a,b)),b.o?a.T("yt-remote-cast2-session-change",b.o):c&&a.g.bk(null)):a.T("yt-remote-cast2-session-change",null))},KCa=function(a){var b=a.l.JF(),c=a.g&&a.g.l;
a=(0,g.G)(b,function(a){c&&W6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=JCa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},QCa=function(a,b,c,d,e,f,k){LCa()?MCa(b,e,f,k)&&(s8(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?NCa(a,c):(window.__onGCastApiAvailable=function(b,d){b?NCa(a,c):(t8("Failed to load cast API: "+d),u8(!1),s8(!1),g.SG("yt-remote-cast-available"),g.SG("yt-remote-cast-receiver"),OCa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):BBa():l7("CriOS")?GBa():l7("Android")&&l7("Chrome/")&&window.navigator.presentation?HBa():window.chrome&&window.navigator.presentation&&!l7("Edge")?(m7(),i7(PCa.map(EBa))):j7())):r8("Cannot initialize because not running Chrome")},OCa=function(){r8("dispose");
var a=v8();a&&a.dispose();g.va("yt.mdx.remote.cloudview.instance_",null,void 0);RCa(!1);g.WF(w8);w8.length=0},x8=function(){return!!g.RG("yt-remote-cast-installed")},SCa=function(){var a=g.RG("yt-remote-cast-receiver");
return a?a.friendlyName:null},TCa=function(){r8("clearCurrentReceiver");
g.SG("yt-remote-cast-receiver")},UCa=function(){return x8()?v8()?v8().getCastSession():(t8("getCastSelector: Cast is not initialized."),null):(t8("getCastSelector: Cast API is not installed!"),null)},z8=function(){x8()?v8()?y8()?(r8("Requesting cast selector."),v8().requestSession()):(r8("Wait for cast API to be ready to request the session."),w8.push(g.VF("yt-remote-cast2-api-ready",z8))):t8("requestCastSelector: Cast is not initialized."):t8("requestCastSelector: Cast API is not installed!")},A8=
function(a,b){y8()?v8().setConnectedScreenStatus(a,b):t8("setConnectedScreenStatus called before ready.")},LCa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.DI||a},VCa=function(a,b){v8().init(a,b)},MCa=function(a,b,c,d){var e=!1;
v8()||(a=new n8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.QG("yt-remote-cast-available",a);g.ZF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){r8("onReceiverSelected: "+a.friendlyName);
g.QG("yt-remote-cast-receiver",a);g.ZF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){r8("onReceiverResumed: "+a.friendlyName);
g.QG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){r8("onSessionChange: "+X6(a));
a||g.SG("yt-remote-cast-receiver");g.ZF("yt-remote-cast2-session-change",a)}),g.va("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
r8("cloudview.createSingleton_: "+e);return e},v8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},NCa=function(a,b){u8(!0);
s8(!1);VCa(a,function(a){a?(RCa(!0),g.YF("yt-remote-cast2-api-ready")):(t8("Failed to initialize cast API."),u8(!1),g.SG("yt-remote-cast-available"),g.SG("yt-remote-cast-receiver"),OCa());b(a)})},r8=function(a){T7("cloudview",a)},t8=function(a){T7("cloudview",a)},u8=function(a){r8("setCastInstalled_ "+a);
g.QG("yt-remote-cast-installed",a)},y8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},RCa=function(a){r8("setApiReady_ "+a);
g.va("yt.mdx.remote.cloudview.apiReady_",a,void 0)},s8=function(a){g.va("yt.mdx.remote.cloudview.initializing_",a,void 0)},B8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Xf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},C8=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Xf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.F)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},D8=function(a){return a.kb()?((0,g.F)()-a.D)/1E3:0},E8=function(a,b){a.F=b;
a.D=(0,g.F)()},F8=function(a){switch(a.g){case 1:case 1081:return((0,g.F)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},G8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&C8(a)},H8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.l);b.hasPrevious=a.Xf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},J8=function(a,b){g.JF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.oC;this.o=this.l=null;this.H=(0,g.z)(this.VQ,this);this.D=(0,g.z)(this.wm,this);this.F=(0,g.z)(this.UQ,this);this.I=(0,g.z)(this.hR,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.rw,this),WCa(this))):c=3;0!=c&&(b?this.rw(c):g.YD((0,g.z)(function(){this.rw(c)},this),0));
var d=UCa();d&&I8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},K8=function(a){return new B8(a.A.getPlayerContextData())},WCa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Ga(this.wT,a),this))},a)},XCa=function(a){(0,g.B)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},L8=function(a,b){50>a.B.Dc()&&g.qC(a.B,b)},N8=function(a,b,c){var d=K8(a);
E8(d,c);-1E3!=d.g&&(d.g=b);M8(a,d)},O8=function(a,b,c){a.A.sendMessage(b,c)},M8=function(a,b){XCa(a);
a.A.setPlayerContextData(H8(b));WCa(a)},I8=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.wm(null));
a.o=b;a.o&&(T7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.wm(a.o.media[0]))},YCa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=K8(a);b.contentId!=d.videoId&&T7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;E8(d,a.l.getEstimatedTime());M8(a,d)}else T7("CP","No cast media video. Ignoring state update.")},P8=function(a,b,c){return(0,g.z)(function(a){this.fc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.fc("Retrying "+b+" using MDx browser channel."),O8(this,b,c))},a)},Q8=function(a,b,c){g.JF.call(this);
this.B=window.NaN;this.M=!1;this.I=this.H=this.J=this.K=window.NaN;this.R=[];this.A=this.D=this.o=this.Za=this.g=null;this.ra=a;this.R.push(g.sF(window,"beforeunload",(0,g.z)(this.YJ,this)));this.l=[];this.Za=new B8;this.Z=b.id;this.g=ZCa(this,c);this.g.subscribe("handlerOpened",this.ZQ,this);this.g.subscribe("handlerClosed",this.WQ,this);this.g.subscribe("handlerError",this.XQ,this);this.g.subscribe("handlerMessage",this.YQ,this);lCa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Za.videoId;g.TG()&&g.QG("yt-remote-session-video-id",a)},this)},R8=function(a){T7("conn",a)},ZCa=function(a,b){return new N7(Q7(a.ra,"/bc"),b)},S8=function(a,b){a.T("proxyStateChange",b)},$Ca=function(a){a.B=g.YD((0,g.z)(function(){R8("Connecting timeout");
this.C(1)},a),2E4)},T8=function(a){g.$D(a.B);
a.B=window.NaN},U8=function(a){g.$D(a.K);
a.K=window.NaN},aDa=function(a){V8(a);
a.J=g.YD((0,g.z)(function(){W8(this,"getNowPlaying")},a),2E4)},V8=function(a){g.$D(a.J);
a.J=window.NaN},cDa=function(a,b){b&&(T8(a),U8(a));
b==(O7(a.g)&&(0,window.isNaN)(a.B))?b&&(S8(a,1),W8(a,"getSubtitlesTrack")):b?(a.X()&&a.Za.reset(),S8(a,1),W8(a,"getNowPlaying"),bDa(a)):a.C(1)},dDa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Za.videoId&&(g.Xb(b.params)?a.Za.l=null:a.Za.l=b.params,a.T("remotePlayerChange"))},eDa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Za.listId=b.params.listId||a.Za.listId;G8(a.Za,c,d);a.T("remoteQueueChange")},gDa=function(a,b){b.params=b.params||{};
eDa(a,b);fDa(a,b);a.T("autoplayDismissed")},fDa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
E8(a.Za,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Za.g&&(c=-1E3);a.Za.g=c;c=Number(b.params.loadedTime);a.Za.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Za.H=(0,window.isNaN)(c)?0:c;c=a.Za;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Za;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Za.g?aDa(a):V8(a);
a.T("remotePlayerChange")},hDa=function(a,b){if(-1E3!=a.Za.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Za.g=c;c=(0,window.parseInt)(b.params.currentTime,10);E8(a.Za,(0,window.isNaN)(c)?0:c);a.T("remotePlayerChange")}},iDa=function(a,b){var c="true"==b.params.muted;
a.Za.volume=(0,window.parseInt)(b.params.volume,10);a.Za.muted=c;a.T("remotePlayerChange")},jDa=function(a,b){a.D=b.params.videoId;
a.T("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},kDa=function(a,b){var c="true"==b.params.hasNext;
a.Za.Xf="true"==b.params.hasPrevious;a.Za.hasNext=c;a.T("previousNextChange")},bDa=function(a){g.$D(a.I);
a.I=g.YD((0,g.z)(a.C,a,1),864E5)},W8=function(a,b,c){c?R8("Sending: action="+b+", params="+g.yg(c)):R8("Sending: action="+b);
a.g.sendMessage(b,c)},X8=function(a){X7.call(this,"ScreenServiceProxy");
this.fd=a;this.l=[];this.l.push(this.fd.$_s("screenChange",(0,g.z)(this.aX,this)));this.l.push(this.fd.$_s("onlineScreenChange",(0,g.z)(this.YS,this)))},pDa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.SD("MDX_CONFIG")||b;qBa();e7();Y8||(Y8=new P7(b?b.loungeApiHost:void 0),yBa()&&(Y8.g="/api/loungedev"));Z8||(Z8=g.x("yt.mdx.remote.deferredProxies_")||[],g.va("yt.mdx.remote.deferredProxies_",Z8,void 0));lDa();var c=$8();if(!c){var d=new f8(Y8);g.va("yt.mdx.remote.screenService_",d,void 0);c=$8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);QCa(a,d,function(a){a?a9()&&A8(a9(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.ZF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.va("yt.mdx.remote.initialized_",!0,void 0),b9("Initializing: "+g.yg(b)),c9.push(g.VF("yt-remote-cast2-availability-change",function(){g.ZF("yt-remote-receiver-availability-change")})),c9.push(g.VF("yt-remote-cast2-receiver-selected",function(){d9(null);
g.ZF("yt-remote-auto-connect","cast-selector-receiver")})),c9.push(g.VF("yt-remote-cast2-receiver-resumed",function(){g.ZF("yt-remote-receiver-resumed","cast-selector-receiver")})),c9.push(g.VF("yt-remote-cast2-session-change",mDa)),c9.push(g.VF("yt-remote-connection-change",function(a){a?A8(a9(),"YouTube TV"):e9()||(A8(null,null),TCa())})),a=f9(),b.isAuto&&(a.id+="#dial"),g.PF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),b9(" -- with channel params: "+
g.yg(a)),nDa(a),c.start(),a9()||oDa())},rDa=function(){var a=qDa();
x8()&&g.RG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},qDa=function(){var a=$8().fd.$_gos();
var b=g9();b&&h9()&&($6(a,b)||a.push(b));return pBa(a)},i9=function(){var a=sDa();
!a&&x8()&&SCa()&&(a={key:"cast-selector-receiver",name:SCa()});return a},sDa=function(){var a=qDa(),b=g9();
b||(b=e9());return g.La(a,function(a){return b&&W6(b,a.key)?!0:!1})},g9=function(){var a=a9();
if(!a)return null;var b=$8().oe();return a7(b,a)},mDa=function(a){b9("remote.onCastSessionChange_: "+X6(a));
if(a){var b=g9();b&&b.id==a.id?A8(b.id,"YouTube TV"):(b&&j9(),k9(a,1))}else h9()&&j9()},j9=function(){y8()?v8().stopSession():t8("stopSession called before API ready.");
var a=h9();a&&(a.disconnect(1),l9(null))},m9=function(){var a=h9();
return!!a&&3!=a.getProxyState()},b9=function(a){T7("remote",a)},$8=function(){if(!n9){var a=g.x("yt.mdx.remote.screenService_");
n9=a?new X8(a):null}return n9},a9=function(){return g.x("yt.mdx.remote.currentScreenId_")},tDa=function(a){g.va("yt.mdx.remote.currentScreenId_",a,void 0)},uDa=function(){return g.x("yt.mdx.remote.connectData_")},d9=function(a){g.va("yt.mdx.remote.connectData_",a,void 0)},h9=function(){return g.x("yt.mdx.remote.connection_")},l9=function(a){var b=h9();
d9(null);a||tDa("");g.va("yt.mdx.remote.connection_",a,void 0);Z8&&((0,g.B)(Z8,function(b){b(a)}),Z8.length=0);
b&&!a?g.ZF("yt-remote-connection-change",!1):!b&&a&&g.ZF("yt-remote-connection-change",!0)},e9=function(){var a=g.TG();
if(!a)return null;var b=$8().oe();return a7(b,a)},k9=function(a,b){g9()&&g9();
tDa(a.id);var c=new Q8(Y8,a,f9());c.connect(b,uDa());c.subscribe("beforeDisconnect",function(a){g.ZF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){h9()&&l9(null)});
l9(c)},oDa=function(){var a=e9();
a?(b9("Resume connection to: "+X6(a)),k9(a,0)):(f7(),TCa(),b9("Skipping connecting because no session screen found."))},lDa=function(){var a=f9();
if(g.Xb(a)){a=d7();var b=g.RG("yt-remote-session-name")||"",c=g.RG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.va("yt.mdx.remote.channelParams_",a,void 0)}},f9=function(){return g.x("yt.mdx.remote.channelParams_")||{}},nDa=function(a){a?(g.QG("yt-remote-session-app",a.app),g.QG("yt-remote-session-name",a.name)):(g.SG("yt-remote-session-app"),g.SG("yt-remote-session-name"));
g.va("yt.mdx.remote.channelParams_",a,void 0)},o9=function(a,b,c){g.M.call(this);
this.F=a;this.l=b;this.o=new g.GF(this);g.N(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.pS);this.o.O(b,"captionschanged",this.TQ);this.o.O(b,"captionssettingschanged",this.WE);this.o.O(b,"videoplayerreset",this.Dp);this.o.O(b,"mdxautoplaycancel",this.fJ);this.R=this.o.O(b,"onVolumeChange",this.ZC);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.mD,this);c.subscribe("remotePlayerChange",this.zm,this);c.subscribe("remoteQueueChange",this.Dp,this);c.subscribe("autoplayUpNext",this.KC,
this);c.subscribe("previousNextChange",this.jD,this);c.subscribe("nowAutoplaying",this.bD,this);c.subscribe("autoplayDismissed",this.JC,this);this.suggestion=null;this.H=new g.rP(64);this.A=new g.Xt(this.SE,500,this);g.N(this,this.A);this.B=new g.Xt(this.TE,1E3,this);g.N(this,this.B);this.J=new n7(this.BW,0,this);g.N(this,this.J);this.C={};this.K=new g.Xt(this.tF,1E3,this);g.N(this,this.K);this.I=new g.Uk(this.SO,1E3,this);g.N(this,this.I);this.M=g.y;this.WE();this.Dp();this.zm()},p9=function(a,b){var c=
a.F,d=a.l.getVideoData().lengthSeconds;
c.H=b||0;c.g.T("progresssync",b,d)},vDa=function(a){p9(a,0);
a.A.stop();q9(a,new g.rP(64))},s9=function(a,b){if(r9(a)&&!a.D){var c=null;
b&&(c={style:a.l.Ki()},g.ec(c,b));a.g.GE(a.l.getVideoData(1).videoId,c);a.C=K8(a.g).l}},t9=function(a,b){var c=a.l.fg();
if(c){var d=c.ke();var e=c.listId.toString()}var f=a.l.getVideoData(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;var m=f.Uj;f=fBa(f);var n=K8(c);l=l||0;var p={videoId:k,currentIndex:l};G8(n,k,l);g.t(b)&&(E8(n,b),p.currentTime=b);g.t(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.yg(f));O8(c,"setPlaylist",p);e||M8(c,n);q9(a,new g.rP(1))},wDa=function(a,b){if(b){var c=a.l.xc("captions","tracklist",{nA:1});
c&&c.length?(a.l.Od("captions","track",b),a.D=!1):(a.l.kk("captions"),a.D=!0)}else a.l.Od("captions","track",{})},r9=function(a){return K8(a.g).videoId==a.l.getVideoData(1).videoId},q9=function(a,b){a.B.stop();
var c=a.H;if(!g.wP(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.VU(a.l,d);a.H=b;xDa(a.F,c,b)}},u9=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",N:[{G:"div",L:"ytp-remote-display-status",N:[{G:"div",L:"ytp-remote-display-status-icon",N:[g.Zoa()]},{G:"div",L:"ytp-remote-display-status-text",aa:"{{statustext}}"}]}]});this.l=new g.LV(this,250);g.N(this,this.l);this.A=a;this.O(a,"presentingplayerstatechange",this.B);yDa(this,g.SU(a))},yDa=function(a,b){if(3==a.A.Oa()){var c={RECEIVER_NAME:a.A.xc("remote","currentReceiver").name};
c=g.X(b,128)?g.O0("Erro em $RECEIVER_NAME",c):b.kb()||g.X(b,4)?g.O0("Reproduzindo em $RECEIVER_NAME",c):g.O0("Conectado a $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},v9=function(a,b){g.UZ.call(this,"Reproduzir em",0,a,b);
this.l=a;this.H={};this.O(a,"onMdxReceiversChange",this.J);this.O(a,"presentingplayerstatechange",this.J);this.J()},w9=function(a){g.rV.call(this,a);
this.o={key:Z6(),name:"Este computador"};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.rP(64);this.H=0;if(!g.VM(g.Y(this.g))){a=this.g;var b=g.IH(a);b&&(b=b.Yo())&&(b=new v9(a,b),g.N(this,b));b=new u9(a);g.N(this,b);g.kV(a,b.element,4)}},xDa=function(a,b,c){a.D=c;
a.g.T("presentingplayerstatechange",new g.BP(c,b))},x9=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)j9();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.getVideoData(1);var e=d.videoId;if(c||e){var f=a.g.fg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Yb(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Uj,index:Math.max(a.g.rB(),0),currentTime:0==f?void 0:f};(d=fBa(d))&&(c.locationInfo=d);d=c}else d=null;b9("Connecting to: "+g.yg(b));"cast-selector-receiver"==b.key?(d9(d||null),y8()?v8().setLaunchParams(d||null):
t8("setLaunchParams called before ready.")):!d&&m9()&&a9()==b.key?g.ZF("yt-remote-connection-change",!0):(j9(),d9(d||null),d=$8().oe(),(d=a7(d,b.key))&&k9(d,1))}},NBa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},x7={"'":"\\'"},zDa={},lBa={qY:"atp",S2:"ska",f2:"que",q1:"mus",O2:"sus",y_:"dsp"};
U6.prototype.Rn=function(){var a=new U6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var g7,c7="",k7=h7("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",FBa=h7("loadCastFramework")||h7("loadCastApplicationFramework"),PCa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(n7,g.M);g.h=n7.prototype;g.h.TJ=function(a){this.A=arguments;this.g=!1;this.Ca?this.o=(0,g.F)()+this.qd:this.Ca=g.sg(this.B,this.qd)};
g.h.stop=function(){this.Ca&&(g.tg(this.Ca),this.Ca=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();n7.ba.V.call(this)};
g.h.UJ=function(){this.o?(this.Ca=g.sg(this.B,this.o-(0,g.F)()),this.o=null):(this.Ca=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};o7.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
o7.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=p7.prototype;g.h.ni=null;g.h.Ef=!1;g.h.Sk=null;g.h.jw=null;g.h.Ck=null;g.h.Lj=null;g.h.mh=null;g.h.Jh=null;g.h.Si=null;g.h.Qc=null;g.h.Tm=0;g.h.Ff=null;g.h.Dq=null;g.h.nh=null;g.h.Il=-1;g.h.lE=!0;g.h.Xh=!1;g.h.Gs=0;g.h.Pp=null;var LBa={},s7={};g.h=p7.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.tV=function(a){a=a.target;var b=this.Pp;b&&3==g.hx(a)?b.Jj():this.DF(a)};
g.h.DF=function(a){try{if(a==this.Qc)a:{var b=g.hx(this.Qc),c=this.Qc.l,d=this.Qc.getStatus();if(g.xd&&!g.tc(10)||g.zd&&!g.qc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.cf&&!g.lx(this.Qc))break a;this.Xh||4!=b||7==c||(8==c||0>=d?this.g.yf(3):this.g.yf(2));z7(this);var e=this.Qc.getStatus();this.Il=e;var f=g.lx(this.Qc);(this.Ef=200==e)?(4==b&&v7(this),this.B?(MBa(this,b,f),g.cf&&this.Ef&&3==b&&(this.W.U(this.l,"tick",this.pV),this.l.start())):u7(this,f),this.Ef&&!this.Xh&&(4==b?this.g.Bp(this):
(this.Ef=!1,r7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.nh=3,t7(13)):(this.nh=0,t7(14)),v7(this),w7(this))}}catch(k){this.Qc&&g.lx(this.Qc)}finally{}};
g.h.pV=function(){var a=g.hx(this.Qc),b=g.lx(this.Qc);this.Tm<b.length&&(z7(this),MBa(this,a,b),this.Ef&&4!=a&&r7(this))};
g.h.CU=function(a){y7((0,g.z)(this.BU,this,a),0)};
g.h.BU=function(a){this.Xh||(z7(this),u7(this,a),r7(this))};
g.h.uD=function(a){y7((0,g.z)(this.AU,this,a),0)};
g.h.AU=function(a){this.Xh||(v7(this),this.Ef=a,this.g.Bp(this),this.g.yf(4))};
g.h.cancel=function(){this.Xh=!0;v7(this)};
g.h.SU=function(){this.Sk=null;var a=(0,g.F)();0<=a-this.jw?(2!=this.Lj&&this.g.yf(3),v7(this),this.nh=2,t7(18),w7(this)):PBa(this,this.jw-a)};g.h=SBa.prototype;g.h.Es=null;g.h.we=null;g.h.Qp=!1;g.h.Dz=null;g.h.fo=null;g.h.Lt=null;g.h.Fs=null;g.h.Ne=null;g.h.Dg=-1;g.h.Hl=null;g.h.dl=null;g.h.connect=function(a){this.Fs=a;a=B7(this.g,null,this.Fs);t7(3);this.Dz=(0,g.F)();var b=this.g.F;null!=b?(this.Hl=b[0],(this.dl=b[1])?(this.Ne=1,TBa(this)):(this.Ne=2,D7(this))):(T6(a,"MODE","init"),this.we=new p7(this,void 0,void 0,void 0),this.we.ni=this.Es,q7(this.we,a,!1,null,!0),this.Ne=0)};
g.h.gJ=function(a){if(a)this.Ne=2,D7(this);else{t7(4);var b=this.g;b.Uf=b.ah.Dg;K7(b,9)}a&&this.yf(2)};
g.h.Rr=function(a){return this.g.Rr(a)};
g.h.abort=function(){this.we&&(this.we.cancel(),this.we=null);this.Dg=-1};
g.h.Cz=function(){return!1};
g.h.nD=function(a,b){this.Dg=a.Il;if(0==this.Ne)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Uf=this.Dg;K7(c,2);return}this.Hl=c[0];this.dl=c[1]}else c=this.g,c.Uf=this.Dg,K7(c,2);else if(2==this.Ne)if(this.Qp)t7(7),this.Lt=(0,g.F)();else if("11111"==b){if(t7(6),this.Qp=!0,this.fo=(0,g.F)(),c=this.fo-this.Dz,!g.xd||g.tc(10)||500>c)this.Dg=200,this.we.cancel(),t7(12),C7(this.g,this,!0)}else t7(8),this.fo=this.Lt=(0,g.F)(),this.Qp=!1};
g.h.Bp=function(){this.Dg=this.we.Il;if(this.we.Ef)0==this.Ne?this.dl?(this.Ne=1,TBa(this)):(this.Ne=2,D7(this)):2==this.Ne&&((!g.xd||g.tc(10)?!this.Qp:200>this.Lt-this.fo)?(t7(11),C7(this.g,this,!1)):(t7(12),C7(this.g,this,!0)));else{0==this.Ne?t7(9):2==this.Ne&&t7(10);var a=this.g;a.Uf=this.Dg;K7(a,2)}};
g.h.Jm=function(){return this.g.Jm()};
g.h.isActive=function(){return this.g.isActive()};
g.h.yf=function(a){this.g.yf(a)};g.h=E7.prototype;g.h.tl=null;g.h.be=null;g.h.tc=null;g.h.Ds=null;g.h.lo=null;g.h.Ox=null;g.h.yo=null;g.h.rm=0;g.h.lQ=0;g.h.pd=null;g.h.eh=null;g.h.sg=null;g.h.ci=null;g.h.ah=null;g.h.Cq=null;g.h.Zj=-1;g.h.DA=-1;g.h.Uf=-1;g.h.Aj=0;g.h.nj=0;g.h.Zh=8;var L7=new g.Cf;g.A(VBa,g.af);g.A(WBa,g.af);g.A(XBa,g.af);g.h=E7.prototype;g.h.connect=function(a,b,c,d,e){t7(0);this.Ds=b;this.tl=c||{};d&&g.t(e)&&(this.tl.OSID=d,this.tl.OAID=e);this.C?(y7((0,g.z)(this.ly,this,a),100),aCa(this)):this.ly(a)};
g.h.ly=function(a){this.ah=new SBa(this);this.ah.Es=null;this.ah.l=this.B;this.ah.connect(a)};
g.h.Cz=function(){return 0==this.g};
g.h.sD=function(a){this.eh=null;dCa(this,a)};
g.h.rD=function(){this.sg=null;this.tc=new p7(this,this.o,"rpc",this.D);this.tc.ni=null;this.tc.Gs=0;var a=this.Ox.clone();g.Em(a,"RID","rpc");g.Em(a,"SID",this.o);g.Em(a,"CI",this.Cq?"0":"1");g.Em(a,"AID",this.Zj);F7(this,a);if(!g.xd||g.tc(10))g.Em(a,"TYPE","xmlhttp"),q7(this.tc,a,!0,this.yo,!1);else{g.Em(a,"TYPE","html");var b=this.tc,c=!!this.yo;b.Lj=3;b.mh=S6(a.clone());OBa(b,c)}};
g.h.nD=function(a,b){if(0!=this.g&&(this.tc==a||this.be==a))if(this.Uf=a.Il,this.be==a&&3==this.g)if(7<this.Zh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.Aa(c)&&3==c.length)if(0==c[0])a:{if(!this.sg){if(this.tc)if(this.tc.Ck+3E3<this.be.Ck)H7(this),this.tc.cancel(),this.tc=null;else break a;J7(this);t7(19)}}else this.DA=c[1],0<this.DA-this.Zj&&37500>c[2]&&this.Cq&&0==this.nj&&!this.ci&&(this.ci=y7((0,g.z)(this.OQ,this),6E3));else K7(this,11)}else b!=zDa.tZ.g&&K7(this,11);else if(this.tc==a&&
H7(this),!g.C(b)){c=this.B.parse(b);g.Aa(c);for(var d=0;d<c.length;d++){var e=c[d];this.Zj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.yo=e[2],e=e[3],null!=e?this.Zh=e:this.Zh=6,this.g=3,this.pd&&this.pd.ay(),this.Ox=B7(this,this.Jm()?this.yo:null,this.Ds),eCa(this)):"stop"==e[0]&&K7(this,7):3==this.g&&("stop"==e[0]?K7(this,7):"noop"!=e[0]&&this.pd&&this.pd.Zx(e),this.nj=0)}}};
g.h.OQ=function(){null!=this.ci&&(this.ci=null,this.tc.cancel(),this.tc=null,J7(this),t7(20))};
g.h.Bp=function(a){if(this.tc==a){H7(this);this.tc=null;var b=2}else if(this.be==a)this.be=null,b=1;else return;this.Uf=a.Il;if(0!=this.g)if(a.Ef)1==b?(b=(0,g.F)()-a.Ck,L7.dispatchEvent(new WBa(L7,a.Si?a.Si.length:0,b,this.Aj)),G7(this),this.A.length=0):eCa(this);else{var c=a.nh,d;if(!(d=3==c||7==c||0==c&&0<this.Uf)){if(d=1==b)this.be||this.eh||1==this.g||2<=this.Aj?d=!1:(this.eh=y7((0,g.z)(this.sD,this,a),fCa(this,this.Aj)),this.Aj++,d=!0);d=!(d||2==b&&J7(this))}if(d)switch(c){case 1:K7(this,5);
break;case 4:K7(this,10);break;case 3:K7(this,6);break;case 7:K7(this,12);break;default:K7(this,2)}}};
g.h.BJ=function(a){if(!g.Pa(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.mW=function(a){a?t7(2):(t7(1),gCa(this,8))};
g.h.Rr=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.bx;a.F=!1;return a};
g.h.isActive=function(){return!!this.pd&&this.pd.isActive(this)};
g.h.yf=function(a){L7.dispatchEvent(new XBa(L7,a))};
g.h.Jm=function(){return!(!g.xd||g.tc(10))};
g.h=hCa.prototype;g.h.ay=function(){};
g.h.Zx=function(){};
g.h.Yx=function(){};
g.h.Er=function(){};
g.h.hz=function(){return{}};
g.h.isActive=function(){return!0};g.A(M7,g.M);g.h=M7.prototype;g.h.tU=function(){this.qd=Math.min(3E5,2*this.qd);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.qd+15E3*Math.random();g.Yt(this.g,a);this.l=(0,g.F)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.qd=5E3};g.A(N7,hCa);g.h=N7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Td=function(a){return this.o.Td(a)};
g.h.T=function(a,b){return this.o.T.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.Ze(this.o),kCa(this),g.Ze(this.l),this.l=null)};
g.h.ka=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new E7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.K),e=this.g;e&&(e.pd=null);d.pd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Zj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):O7(this)&&bCa(this.g,c)};
g.h.ay=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)bCa(this.g,a[b])}this.T("handlerOpened")};
g.h.Yx=function(a){var b=2==a&&401==this.g.Uf;4==a||b||this.l.start();this.T("handlerError",a)};
g.h.Er=function(a){if(!this.l.isActive())this.T("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.hz=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.ec(a,this.B);return a};
g.h.Zx=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),$Ba(this.g)):this.T("handlerMessage",new iCa(a[0],a[1]))};
g.h.WW=function(){this.l.isActive();var a=this.g,b=0;a.tc&&b++;a.be&&b++;0!=b||this.connect(this.B,this.A)};P7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
P7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
P7.prototype.B=function(a){a(Error("request timed out"))};var sCa=(0,g.F)(),S7=null,V7=Array(50),U7=-1,W7=!1;g.A(X7,g.JF);X7.prototype.oe=function(){return this.g};
X7.prototype.contains=function(a){return!!$6(this.g,a)};
X7.prototype.get=function(a){return a?a7(this.g,a):null};
X7.prototype.info=function(a){T7(this.D,a)};g.A(Y7,g.JF);var ADa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=Y7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Ca)&&this.IF()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Ca)||(g.$D(this.Ca),this.Ca=window.NaN)};
g.h.V=function(){this.stop();Y7.ba.V.call(this)};
g.h.IF=function(){this.Ca=window.NaN;this.g=g.oE(Q7(this.C,"/pairing/get_screen"),{method:"POST",Nb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.z)(this.YW,this),onError:(0,g.z)(this.XW,this),wd:(0,g.z)(this.ZW,this)})};
g.h.YW=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.T("pairingComplete",new V6(c))};
g.h.XW=function(a){this.g=null;a.status&&404==a.status?this.l>=ADa.length?this.T("pairingFailed",Error("DIAL polling timed out")):(a=ADa[this.l],this.Ca=g.YD((0,g.z)(this.IF,this),a),this.l++):this.T("pairingFailed",Error("Server error "+a.status))};
g.h.ZW=function(){this.g=null;this.T("pairingFailed",Error("Server not responding"))};g.A($7,X7);g.h=$7.prototype;g.h.start=function(){Z7(this)&&this.T("screenChange");!g.RG("yt-remote-lounge-token-expiration")&&wCa(this);g.$D(this.l);this.l=g.YD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){Z7(this);tCa(this,a);a8(this,!1);this.T("screenChange");b(a);a.token||wCa(this)};
g.h.remove=function(a,b){var c=Z7(this);vCa(this,a)&&(a8(this,!1),c=!0);b(a);c&&this.T("screenChange")};
g.h.xq=function(a,b,c,d){var e=Z7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,a8(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.T("screenChange")};
g.h.V=function(){g.$D(this.l);$7.ba.V.call(this)};
g.h.hK=function(a){Z7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}a8(this,!b);b&&T7(this.D,"Missed "+b+" lounge tokens.")};
g.h.gK=function(a){T7(this.D,"Requesting lounge tokens failed: "+a)};g.A(c8,g.JF);g.h=c8.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.RG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.F)()-144E5<a?0:a)?e8(this):(this.A=(0,g.F)()+3E5,g.QG("yt-remote-fast-check-period",this.A),this.zv())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){b8("Updating availability on schedule.");var a=this.C(),b=g.Lb(this.g,function(b,d){return b&&!!a7(a,d)},this);
d8(this,b)};
g.h.V=function(){g.$D(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);c8.ba.V.call(this)};
g.h.zv=function(){g.$D(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=zCa(this);if(g.Ob(a)){var b=Q7(this.B,"/pairing/get_screen_availability");this.l=R7(this.B,b,{lounge_token:g.Rb(a).join(",")},(0,g.z)(this.ZT,this,a),(0,g.z)(this.XT,this))}else d8(this,{}),e8(this)};
g.h.ZT=function(a,b){this.l=null;var c=g.Rb(zCa(this));if(g.ib(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;d8(this,d);e8(this)}else this.fc("Changing Screen set during request."),this.zv()};
g.h.XT=function(a){this.fc("Screen availability failed: "+a);this.l=null;e8(this)};
g.h.fc=function(a){T7("OnlineScreenService",a)};g.A(f8,X7);g.h=f8.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.T("screenChange"),this.l.isEmpty()||this.T("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.xq=function(a,b,c,d){this.o.contains(a)?this.o.xq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,T7(this.D,a),d(Error(a)))};
g.h.oe=function(a){return a?this.g:g.Wa(this.g,(0,g.Kd)(this.A,function(a){return!this.contains(a)},this))};
g.h.JF=function(){return(0,g.Kd)(this.oe(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.KF=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new Y7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.Ze(f);d(g8(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Ze(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.bX=function(a,b,c,d){g.oE(Q7(this.C,"/pairing/get_screen"),{method:"POST",Nb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(a,d){var e=new V6(d.screen||{});if(!e.name||DCa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);DCa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(g8(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
wd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.Ze(this.o);g.Ze(this.l);f8.ba.V.call(this)};
g.h.wK=function(){ECa(this);this.T("screenChange");this.l.update()};
f8.prototype.dispose=f8.prototype.dispose;g.A(i8,g.JF);g.h=i8.prototype;g.h.Cp=function(a){this.o=a;this.T("sessionScreen",this.o)};
g.h.te=function(a){this.ka()||(a&&j8(this,""+a),this.o=null,this.T("sessionScreen",null))};
g.h.info=function(a){T7(this.K,a)};
g.h.MF=function(){return null};
g.h.Fv=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){j8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.Fv("");i8.ba.V.call(this)};g.A(k8,i8);g.h=k8.prototype;g.h.Ev=function(a){if(this.g){if(this.g==a)return;j8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);GCa(this)};
g.h.bk=function(a){this.info("launchWithParams no-op for Cast: "+g.yg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.te()},this),(0,g.z)(function(){this.te(Error("Failed to stop receiver app."))},this)):this.te(Error("Stopping cast device witout session."))};
g.h.Fv=g.y;g.h.V=function(){this.info("disposeInternal");g.$D(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;k8.ba.V.call(this)};
g.h.eV=function(a,b){if(!this.ka())if(b){var c=g.Ww(b);if(g.Da(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.yg(c));switch(d){case "mdxSessionStatus":FCa(this,c.screenId);break;default:j8(this,"Unknown youtube message: "+d)}}else j8(this,"Unable to parse message.")}else j8(this,"No data in message.")};
g.h.rz=function(a,b,c,d){CCa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(j8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.YD((0,g.z)(this.rz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.MF=function(){return this.g};
g.h.cX=function(a){this.ka()||a||(j8(this,"Cast session died."),this.te())};g.A(l8,i8);g.h=l8.prototype;g.h.Ev=function(a){this.A=a;this.A.addUpdateListener(this.J)};
g.h.bk=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.$D(this.C);this.A?this.A.stop((0,g.z)(this.te,this,null),(0,g.z)(this.te,this,"Failed to stop DIAL device.")):this.te()};
g.h.V=function(){this.g();this.g=g.y;g.$D(this.C);this.A&&this.A.removeUpdateListener(this.J);this.A=null;l8.ba.V.call(this)};
g.h.fX=function(a){this.ka()||a||(j8(this,"DIAL session died."),this.g(),this.g=g.y,this.te())};
g.h.zt=function(a){this.I=Z6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,ICa(this));a(b);HCa(this)}else this.D=(0,g.z)(function(){g.$D(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,ICa(this));a(b);HCa(this)},this),this.C=g.YD((0,g.z)(function(){this.D()},this),100)};
g.h.LL=function(a,b,c){CCa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Cp(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.zt(b,c)},this),(0,g.z)(function(a){j8(this,"Failed to get DIAL screen: "+a);
this.zt(b,c)},this))};g.A(m8,i8);m8.prototype.stop=function(){this.te()};
m8.prototype.Ev=g.y;m8.prototype.bk=function(){g.$D(this.g);this.g=window.NaN;var a=a7(this.H.oe(),this.l.label);a?this.Cp(a):this.te(Error("No such screen"))};
m8.prototype.V=function(){g.$D(this.g);this.g=window.NaN;m8.ba.V.call(this)};g.A(n8,g.JF);g.h=n8.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.oD,this),(0,g.z)(this.FT,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.yR,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ka()||(window.chrome.cast.addReceiverActionListener(this.A),pCa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.LF,this)),this.o=KCa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.fc("Failed to set initial custom receivers: "+g.yg(a))},this)),this.T("yt-remote-cast2-availability-change",p8(this)),b(!0))},this),(0,g.z)(function(a){this.fc("Failed to initialize API: "+g.yg(a));
b(!1)},this))};
g.h.VV=function(a,b){o8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)o8("Unsetting old screen status: "+this.g.l.friendlyName),q8(this,null)}if(a&&b){if(!this.g){c=a7(this.l.oe(),a);if(!c){o8("setConnectedScreenStatus: Unknown screen.");return}var d=JCa(this,c);d||(o8("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.fc("Failed to set initial custom receivers: "+g.yg(a))},this)));
o8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);q8(this,new m8(this.l,d),!0)}this.g.Fv(b)}else o8("setConnectedScreenStatus: no screen.")};
g.h.WV=function(a){this.ka()?this.fc("Setting connection data on disposed cast v2"):this.g?this.g.bk(a):this.fc("Setting connection data without a session")};
g.h.eX=function(){this.ka()?this.fc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),q8(this,null)):o8("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.oD,this),(0,g.z)(this.eU,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.LF,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Ua(g.x("yt.mdx.remote.debug.handlers_")||[],mCa);g.Ze(this.g);n8.ba.V.call(this)};
g.h.fc=function(a){T7("Controller",a)};
g.h.pD=function(a,b){this.g==a&&(b||q8(this,null),this.T("yt-remote-cast2-session-change",b))};
g.h.BT=function(a,b){if(!this.ka())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),o8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)o8("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{o8("onReceiverAction_: Casting to active receiver.");this.g.o&&this.T("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:q8(this,
new m8(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:q8(this,new l8(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:q8(this,new k8(this.l,a));break;default:this.fc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.fc("Stopping receiver w/o session: "+a.friendlyName)}else this.fc("onReceiverAction_ called without receiver.")};
g.h.yR=function(a){if(this.ka())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.fc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.fc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return o8("Reselecting dial screen."),
this.T("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.fc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);q8(this,new l8(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.LL,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.zt,b))};
g.h.oD=function(a){if(!this.ka()){o8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)o8("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),q8(this,new k8(this.l,b),!0);else{this.fc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=a7(this.l.oe(),c.label);
d&&W6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(o8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ze(this.g),this.g=new k8(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.pD,this,this.g)),this.g.bk(null));this.g.Ev(a)}}};
g.h.dX=function(){return this.g?this.g.MF():null};
g.h.eU=function(a){this.ka()||(this.fc("Failed to estabilish a session: "+g.yg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&q8(this,null))};
g.h.FT=function(a){o8("Receiver availability updated: "+a);if(!this.ka()){var b=p8(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;p8(this)!=b&&this.T("yt-remote-cast2-availability-change",p8(this))}};
g.h.LF=function(){this.ka()||(this.o=KCa(this),o8("Updating custom receivers: "+g.yg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.fc("Failed to set custom receivers.")},this)),this.T("yt-remote-cast2-availability-change",p8(this)))};
n8.prototype.setLaunchParams=n8.prototype.WV;n8.prototype.setConnectedScreenStatus=n8.prototype.VV;n8.prototype.stopSession=n8.prototype.eX;n8.prototype.getCastSession=n8.prototype.dX;n8.prototype.requestSession=n8.prototype.requestSession;n8.prototype.init=n8.prototype.init;n8.prototype.dispose=n8.prototype.dispose;var w8=[];g.h=B8.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";C8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Xf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.kb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+D8(this):this.H};
g.h.clone=function(){return new B8(H8(this))};g.A(J8,g.JF);g.h=J8.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,P8(this,"play")):O8(this,"play"),N8(this,1,F8(K8(this))),this.T("remotePlayerChange")):L8(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,P8(this,"pause")):O8(this,"pause"),N8(this,2,F8(K8(this))),this.T("remotePlayerChange")):L8(this,this.pause)};
g.h.HF=function(a){if(1==this.g){if(this.l){var b=K8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,P8(this,"seekTo",{newTime:a}))}else O8(this,"seekTo",{newTime:a});N8(this,3,a);this.T("remotePlayerChange")}else L8(this,g.Ga(this.HF,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,P8(this,"stopVideo")):O8(this,"stopVideo");var a=K8(this);a.index=-1;a.videoId="";C8(a);M8(this,a);this.T("remotePlayerChange")}else L8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=K8(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){T7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.fc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){T7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.fc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);O8(this,"setVolume",e)}c.muted=b;c.volume=a;M8(this,c)}else L8(this,g.Ga(this.setVolume,a,b))};
g.h.GE=function(a,b){if(1==this.g){var c=K8(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.yg(b.style),g.ec(d,c.l));O8(this,"setSubtitlesTrack",d);M8(this,c)}else L8(this,g.Ga(this.GE,a,b))};
g.h.qw=function(a,b){if(1==this.g){O8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Hb.id});var c=K8(this);c.audioTrackId=b.Hb.id;M8(this,c)}else L8(this,g.Ga(this.qw,a,b))};
g.h.GF=function(a,b){if(1==this.g){if(a&&b){var c=K8(this);G8(c,a,b);M8(this,c)}O8(this,"previous")}else L8(this,g.Ga(this.GF,a,b))};
g.h.FF=function(a,b){if(1==this.g){if(a&&b){var c=K8(this);G8(c,a,b);M8(this,c)}O8(this,"next")}else L8(this,g.Ga(this.FF,a,b))};
g.h.Iy=function(){1==this.g?O8(this,"dismissAutoplay"):L8(this,this.Iy)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.T("proxyStateChange",a,this.g)}J8.ba.dispose.call(this)};
g.h.V=function(){XCa(this);this.A=null;this.B.clear();I8(this,null);J8.ba.V.call(this)};
g.h.rw=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.T("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.rC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.wT=function(a,b){this.T(a,b)};
g.h.VQ=function(a){if(!a)this.wm(null),I8(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=K8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)T7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,M8(this,b)}};
g.h.wm=function(a){T7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),YCa(this),this.T("remotePlayerChange")};
g.h.UQ=function(a){a?(YCa(this),this.T("remotePlayerChange")):this.wm(null)};
g.h.hR=function(){var a=UCa();a&&I8(this,a)};
g.h.fc=function(a){T7("CP",a)};g.A(Q8,g.JF);g.h=Q8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Za.listId=c);this.Za.videoId=d;this.Za.index=k||0;this.Za.state=3;E8(this.Za,m);this.A="UNSUPPORTED";R8("Connecting with setPlaylist and params: "+g.yg(l));this.g.connect({method:"setPlaylist",
params:g.yg(l)},a,tBa())}else R8("Connecting without params"),this.g.connect({},a,tBa());$Ca(this)};
g.h.dispose=function(){this.ka()||(this.T("beforeDispose"),S8(this,3));Q8.ba.dispose.call(this)};
g.h.V=function(){T8(this);V8(this);U8(this);g.$D(this.H);this.H=window.NaN;g.$D(this.I);this.I=window.NaN;this.o=null;g.tF(this.R);this.R.length=0;this.g.dispose();Q8.ba.V.call(this);this.A=this.D=this.l=this.Za=this.g=null};
g.h.YJ=function(){this.C(2)};
g.h.ZQ=function(){R8("Channel opened");this.M&&(this.M=!1,U8(this),this.K=g.YD((0,g.z)(function(){R8("Timing out waiting for a screen.");this.C(1)},this),15E3));
xBa(jCa(this.g),this.Z)};
g.h.WQ=function(){R8("Channel closed");(0,window.isNaN)(this.B)?f7(!0):f7();this.dispose()};
g.h.XQ=function(a){f7();(0,window.isNaN)(this.F())?(R8("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,R8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),S8(this,2))};
g.h.YQ=function(a){a.params?R8("Received: action="+a.action+", params="+g.yg(a.params)):R8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Ww(a.params.devices);this.l=(0,g.G)(a,function(a){return new U6(a)});
a=!!g.La(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
cDa(this,a);break;case "loungeScreenDisconnected":g.Va(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
cDa(this,!1);break;case "remoteConnected":var b=new U6(g.Ww(a.params.device));g.La(this.l,function(a){return b?a.id==b.id:!1})||g.Sa(this.l,b);
break;case "remoteDisconnected":b=new U6(g.Ww(a.params.device));g.Va(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":eDa(this,a);break;case "nowPlaying":gDa(this,a);break;case "onStateChange":fDa(this,a);break;case "onAdStateChange":hDa(this,a);break;case "onVolumeChanged":iDa(this,a);break;case "onSubtitlesTrackChanged":dDa(this,a);break;case "nowAutoplaying":jDa(this,a);break;case "autoplayDismissed":this.T("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.T("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.T("autoplayModeChange",this.A);"DISABLED"==this.A&&this.T("autoplayDismissed");break;case "onHasPreviousNextChanged":kDa(this,a);break;case "requestAssistedSignIn":this.T("assistedSignInRequested",a.params.authCode);break;default:R8("Unrecognized action: "+a.action)}};
g.h.FV=function(){if(this.o){var a=this.o;this.o=null;this.Za.videoId!=a&&W8(this,"getNowPlaying")}};
Q8.prototype.subscribe=Q8.prototype.subscribe;Q8.prototype.unsubscribeByKey=Q8.prototype.Td;Q8.prototype.ga=function(){var a=3;this.ka()||(a=0,(0,window.isNaN)(this.F())?O7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
Q8.prototype.getProxyState=Q8.prototype.ga;Q8.prototype.C=function(a){R8("Disconnecting with "+a);T8(this);this.T("beforeDisconnect",a);1==a&&f7();kCa(this.g,a);this.dispose()};
Q8.prototype.disconnect=Q8.prototype.C;Q8.prototype.fa=function(){var a=this.Za;this.o&&(a=this.Za.clone(),G8(a,this.o,a.index));return H8(a)};
Q8.prototype.getPlayerContextData=Q8.prototype.fa;
Q8.prototype.na=function(a){var b=new B8(a);b.videoId&&b.videoId!=this.Za.videoId&&(this.o=b.videoId,g.$D(this.H),this.H=g.YD((0,g.z)(this.FV,this),5E3));var c=[];this.Za.listId==b.listId&&this.Za.videoId==b.videoId&&this.Za.index==b.index||c.push("remoteQueueChange");this.Za.g==b.g&&this.Za.volume==b.volume&&this.Za.muted==b.muted&&F8(this.Za)==F8(b)&&g.yg(this.Za.l)==g.yg(b.l)||c.push("remotePlayerChange");this.Za.reset(a);(0,g.B)(c,function(a){this.T(a)},this)};
Q8.prototype.setPlayerContextData=Q8.prototype.na;Q8.prototype.X=function(){var a=this.g.C.id,b=g.La(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
Q8.prototype.getOtherConnectedRemoteId=Q8.prototype.X;Q8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.F)():window.NaN};
Q8.prototype.getReconnectTimeout=Q8.prototype.F;Q8.prototype.Y=function(){return this.A||"UNSUPPORTED"};
Q8.prototype.getAutoplayMode=Q8.prototype.Y;Q8.prototype.da=function(){return this.D||""};
Q8.prototype.getAutoplayVideoId=Q8.prototype.da;Q8.prototype.ua=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.Zt(a.g);a.start()}};
Q8.prototype.reconnect=Q8.prototype.ua;Q8.prototype.ia=function(a,b){W8(this,a,b);bDa(this)};
Q8.prototype.sendMessage=Q8.prototype.ia;g.A(X8,X7);g.h=X8.prototype;g.h.oe=function(a){return this.fd.$_gs(a)};
g.h.contains=function(a){return!!this.fd.$_c(a)};
g.h.get=function(a){return this.fd.$_g(a)};
g.h.start=function(){this.fd.$_st()};
g.h.add=function(a,b,c){this.fd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.fd.$_r(a,b,c)};
g.h.xq=function(a,b,c,d){this.fd.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.fd.$_ubk(this.l[a]);this.l.length=0;this.fd=null;X8.ba.V.call(this)};
g.h.aX=function(){this.T("screenChange")};
g.h.YS=function(){this.T("onlineScreenChange")};
f8.prototype.$_st=f8.prototype.start;f8.prototype.$_gspc=f8.prototype.bX;f8.prototype.$_gsppc=f8.prototype.KF;f8.prototype.$_c=f8.prototype.contains;f8.prototype.$_g=f8.prototype.get;f8.prototype.$_a=f8.prototype.add;f8.prototype.$_un=f8.prototype.xq;f8.prototype.$_r=f8.prototype.remove;f8.prototype.$_gs=f8.prototype.oe;f8.prototype.$_gos=f8.prototype.JF;f8.prototype.$_s=f8.prototype.subscribe;f8.prototype.$_ubk=f8.prototype.Td;var Y8=null,Z8=null,n9=null,c9=[];g.q(o9,g.M);g.h=o9.prototype;
g.h.V=function(){g.M.prototype.V.call(this);this.A.stop();this.B.stop();this.J.stop();this.M();this.g.unsubscribe("proxyStateChange",this.mD,this);this.g.unsubscribe("remotePlayerChange",this.zm,this);this.g.unsubscribe("remoteQueueChange",this.Dp,this);this.g.unsubscribe("autoplayUpNext",this.KC,this);this.g.unsubscribe("previousNextChange",this.jD,this);this.g.unsubscribe("nowAutoplaying",this.bD,this);this.g.unsubscribe("autoplayDismissed",this.JC,this);this.g=this.F=null};
g.h.LB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(r9(this)){if(!K8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":K8(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.Jj(c[0],c[1]);break;case "control_subtitles_set_track":s9(this,c[0]);break;case "control_set_audio_track":c=c[0],r9(this)&&this.g.qw(this.l.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();t9(this,0==c?void 0:c);break;case "control_seek":t9(this,c[0]);break;case "control_subtitles_set_track":s9(this,c[0]);break;case "control_set_audio_track":c=c[0],r9(this)&&this.g.qw(this.l.getVideoData(1).videoId,c)}};
g.h.TQ=function(a){this.J.TJ(a)};
g.h.BW=function(a){this.LB("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.WE=function(){var a=this.l.xc("captions","track");g.Xb(a)||s9(this,a)};
g.h.ZC=function(a){if(r9(this)){this.g.unsubscribe("remotePlayerChange",this.zm,this);var b=Math.round(a.volume);a=!!a.muted;var c=K8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.K.start();this.g.subscribe("remotePlayerChange",this.zm,this)}};
g.h.pS=function(){g.Xb(this.C)||wDa(this,this.C);this.D=!1};
g.h.mD=function(a,b){this.B.stop();2==b&&this.TE()};
g.h.zm=function(){if(r9(this)){this.A.stop();var a=K8(this.g);switch(a.g){case 1081:case 1:q9(this,new g.rP(8));this.SE();break;case 1085:case 3:q9(this,new g.rP(9));break;case 1083:case 0:q9(this,new g.rP(2));this.I.stop();p9(this,this.l.getVideoData().lengthSeconds);break;case 1084:q9(this,new g.rP(4));break;case 2:q9(this,new g.rP(4));p9(this,F8(a));break;case -1:q9(this,new g.rP(64));break;case -1E3:q9(this,new g.rP(128,{errorCode:"mdx.remoteerror",message:"Este v\u00eddeo n\u00e3o est\u00e1 dispon\u00edvel para reprodu\u00e7\u00e3o remota."}))}a=
K8(this.g).l;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,wDa(this,a));a=K8(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.K.isActive()||this.tF()}else vDa(this)};
g.h.jD=function(){this.l.T("mdxpreviousnextchange")};
g.h.Dp=function(){r9(this)||vDa(this)};
g.h.fJ=function(){this.g.Iy()};
g.h.KC=function(a){a&&(a=g.oE("/watch_queue_ajax",{method:"GET",ad:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.z)(this.FU,this)}))&&(this.M=(0,g.z)(a.abort,a))};
g.h.FU=function(a,b){var c=new g.lO({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.T("mdxautoplayupnext",c)};
g.h.bD=function(a){(0,window.isNaN)(a)||this.l.T("mdxnowautoplaying",a)};
g.h.JC=function(){this.l.T("mdxautoplaycanceled")};
g.h.SO=function(a,b){-1==K8(this.g).g?t9(this,a):b&&this.g.HF(a)};
g.h.tF=function(){if(r9(this)){var a=K8(this.g);this.o.Ea(this.R);a.muted?this.l.mute():this.l.gg();this.l.setVolume(a.volume);this.R=this.o.O(this.l,"onVolumeChange",this.ZC)}};
g.h.SE=function(){this.A.stop();if(!this.g.ka()){var a=K8(this.g);a.kb()&&q9(this,new g.rP(8));p9(this,F8(a));this.A.start()}};
g.h.TE=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.q(u9,g.W);u9.prototype.B=function(a){yDa(this,a.state)};g.q(v9,g.UZ);v9.prototype.J=function(){var a=this.l.xc("remote","receivers");a&&1<a.length&&!this.l.xc("remote","quickCast")?(this.H=g.kb(a,this.C,this),g.VZ(this,(0,g.G)(a,this.C)),a=this.l.xc("remote","currentReceiver"),this.xf(this.C(a)),this.enable(!0)):this.enable(!1)};
v9.prototype.C=function(a){return a.key};
v9.prototype.wf=function(a){return"cast-selector-receiver"==a?"Elenco...":this.H[a].name};
v9.prototype.td=function(a){g.UZ.prototype.td.call(this,a);this.l.Od("remote","currentReceiver",this.H[a]);this.B.Qb()};g.q(w9,g.rV);g.h=w9.prototype;g.h.create=function(){pDa(g.IM(g.Y(this.g)));this.C.push(g.VF("yt-remote-before-disconnect",this.PQ,this));this.C.push(g.VF("yt-remote-connection-change",this.GT,this));this.C.push(g.VF("yt-remote-receiver-availability-change",this.kD,this));this.C.push(g.VF("yt-remote-auto-connect",this.ET,this));this.C.push(g.VF("yt-remote-receiver-resumed",this.DT,this));this.kD()};
g.h.load=function(){this.g.ru();g.rV.prototype.load.call(this);this.B=new o9(this,this.g,this.l);var a=(a=uDa())?a.currentTime:0;var b=m9()?new J8(h9(),void 0):null;0==a&&b&&(a=F8(K8(b)));0!=a&&(this.H=a||0,this.g.T("progresssync",a,void 0));xDa(this,this.D,this.D);g.r0(this.g.app,6)};
g.h.unload=function(){this.g.T("mdxautoplaycanceled");this.A=this.o;g.$e(this.B,this.l);this.l=this.B=null;g.rV.prototype.unload.call(this);g.r0(this.g.app,5)};
g.h.V=function(){g.WF(this.C);g.rV.prototype.V.call(this)};
g.h.km=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.LB.apply(this.B,[a].concat(g.pa(c)))};
g.h.PJ=function(){return this.loaded?this.B.suggestion:null};
g.h.Xf=function(){return this.l?K8(this.l).Xf:!1};
g.h.hasNext=function(){return this.l?K8(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.GO=function(){var a=K8(this.l),b=this.g.getVideoData();return{allowSeeking:this.g.gd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+D8(a):a.A,isPeggedToLive:1>=(a.C?a.o+D8(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+D8(a):a.o,seekableStart:0<a.B?a.B+D8(a):a.B}};
g.h.HO=function(){this.l&&this.l.FF()};
g.h.IO=function(){this.l&&this.l.GF()};
g.h.PQ=function(a){1==a&&(this.I=this.l?K8(this.l):null)};
g.h.GT=function(){var a=m9()?new J8(h9(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.Ze(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.getVideoData().videoId&&this.g.pB(a.videoId,F8(a)));this.g.T("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.kD=function(){this.F=[this.o].concat(rDa());var a=i9()||this.o;x9(this,a);this.g.va("onMdxReceiversChange")};
g.h.ET=function(){var a=i9();x9(this,a)};
g.h.DT=function(){this.A=i9()};
g.h.FO=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?z8():x9(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&z8(),!0):!1}};
g.h.JO=function(){O8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Ac=function(){return!1};g.hY.remote=w9;})(_yt_player);
