(function(configSource){var Ra="function"==typeof Object.defineProperties?Object.defineProperty:function(c,d,a){c!=Array.prototype&&c!=Object.prototype&&(c[d]=a.value)},Xa="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function qb(){qb=function(){};Xa.Symbol||(Xa.Symbol=Hb)}var Hb=function(){var c=0;return function(d){return"jscomp_symbol_"+(d||"")+c++}}();
function Ib(){qb();var c=Xa.Symbol.iterator;c||(c=Xa.Symbol.iterator=Xa.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&Ra(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return Lb(this)}});Ib=function(){}}function Lb(c){var d=0;return Mb(function(){return d<c.length?{done:!1,value:c[d++]}:{done:!0}})}function Mb(c){Ib();c={next:c};c[Xa.Symbol.iterator]=function(){return this};return c}function Nb(c){Ib();var d=c[Symbol.iterator];return d?d.call(c):Lb(c)}
function Ob(c,d){if(d){var a=Xa;c=c.split(".");for(var b=0;b<c.length-1;b++){var k=c[b];k in a||(a[k]={});a=a[k]}c=c[c.length-1];b=a[c];d=d(b);d!=b&&null!=d&&Ra(a,c,{configurable:!0,writable:!0,value:d})}}
Ob("Promise",function(c){function d(a){this.Jg=0;this.Nl=void 0;this.Cg=[];var b=this.Gk();try{a(b.resolve,b.reject)}catch(g){b.reject(g)}}function a(){this.md=null}function b(a){return a instanceof d?a:new d(function(b){b(a)})}if(c)return c;a.prototype.jp=function(a){null==this.md&&(this.md=[],this.wv());this.md.push(a)};a.prototype.wv=function(){var a=this;this.kp(function(){a.mw()})};var k=Xa.setTimeout;a.prototype.kp=function(a){k(a,0)};a.prototype.mw=function(){for(;this.md&&this.md.length;){var a=
this.md;this.md=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(h){this.xv(h)}}}this.md=null};a.prototype.xv=function(a){this.kp(function(){throw a;})};d.prototype.Gk=function(){function a(a){return function(f){c||(c=!0,a.call(b,f))}}var b=this,c=!1;return{resolve:a(this.pz),reject:a(this.Il)}};d.prototype.pz=function(a){if(a===this)this.Il(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof d)this.Nz(a);else{a:switch(typeof a){case "object":var b=null!=a;
break a;case "function":b=!0;break a;default:b=!1}b?this.oz(a):this.Tp(a)}};d.prototype.oz=function(a){var b=void 0;try{b=a.then}catch(g){this.Il(g);return}"function"==typeof b?this.Oz(b,a):this.Tp(a)};d.prototype.Il=function(a){this.pr(2,a)};d.prototype.Tp=function(a){this.pr(1,a)};d.prototype.pr=function(a,b){if(0!=this.Jg)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.Jg);this.Jg=a;this.Nl=b;this.nw()};d.prototype.nw=function(){if(null!=this.Cg){for(var a=this.Cg,
b=0;b<a.length;++b)a[b].call(),a[b]=null;this.Cg=null}};var l=new a;d.prototype.Nz=function(a){var b=this.Gk();a.ii(b.resolve,b.reject)};d.prototype.Oz=function(a,b){var c=this.Gk();try{a.call(b,c.resolve,c.reject)}catch(h){c.reject(h)}};d.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{f(a(b))}catch(t){e(t)}}:b}var f,e,m=new d(function(a,b){f=a;e=b});this.ii(c(a,f),c(b,e));return m};d.prototype.catch=function(a){return this.then(void 0,a)};d.prototype.ii=function(a,
b){function c(){switch(f.Jg){case 1:a(f.Nl);break;case 2:b(f.Nl);break;default:throw Error("Unexpected state: "+f.Jg);}}var f=this;null==this.Cg?l.jp(c):this.Cg.push(function(){l.jp(c)})};d.resolve=b;d.reject=function(a){return new d(function(b,c){c(a)})};d.race=function(a){return new d(function(c,g){for(var f=Nb(a),e=f.next();!e.done;e=f.next())b(e.value).ii(c,g)})};d.all=function(a){var c=Nb(a),g=c.next();return g.done?b([]):new d(function(a,f){function e(b){return function(c){h[b]=c;d--;0==d&&
a(h)}}var h=[],d=0;do h.push(void 0),d++,b(g.value).ii(e(h.length-1),f),g=c.next();while(!g.done)})};return d});function Pb(c,d,a){if(null==c)throw new TypeError("The 'this' value for String.prototype."+a+" must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype."+a+" must not be a regular expression");return c+""}
Ob("String.prototype.startsWith",function(c){return c?c:function(c,a){var b=Pb(this,c,"startsWith");c+="";var d=b.length,l=c.length;a=Math.max(0,Math.min(a|0,b.length));for(var n=0;n<l&&a<d;)if(b[a++]!=c[n++])return!1;return n>=l}});function Qb(c,d){Ib();c instanceof String&&(c+="");var a=0,b={next:function(){if(a<c.length){var k=a++;return{value:d(k,c[k]),done:!1}}b.next=function(){return{done:!0,value:void 0}};return b.next()}};b[Symbol.iterator]=function(){return b};return b}
Ob("Array.prototype.keys",function(c){return c?c:function(){return Qb(this,function(c){return c})}});Ob("Array.prototype.entries",function(c){return c?c:function(){return Qb(this,function(c,a){return[c,a]})}});Ob("Object.getOwnPropertySymbols",function(c){return c?c:function(){return[]}});
Ob("Array.from",function(c){return c?c:function(c,a,b){Ib();a=null!=a?a:function(a){return a};var d=[],l=c[Symbol.iterator];if("function"==typeof l)for(c=l.call(c);!(l=c.next()).done;)d.push(a.call(b,l.value));else{l=c.length;for(var n=0;n<l;n++)d.push(a.call(b,c[n]))}return d}});
Ob("String.prototype.endsWith",function(c){return c?c:function(c,a){var b=Pb(this,c,"endsWith");c+="";void 0===a&&(a=b.length);a=Math.max(0,Math.min(a|0,b.length));for(var d=c.length;0<d&&0<a;)if(b[--a]!=c[--d])return!1;return 0>=d}});Ob("Array.prototype.find",function(c){return c?c:function(c,a){a:{var b=this;b instanceof String&&(b=String(b));for(var d=b.length,l=0;l<d;l++){var n=b[l];if(c.call(a,n,l,b)){c=n;break a}}c=void 0}return c}});var Rb;
if("function"==typeof Object.setPrototypeOf)Rb=Object.setPrototypeOf;else{var Ub;a:{var Vb={Se:!0},Wb={};try{Wb.__proto__=Vb;Ub=Wb.Se;break a}catch(c){}Ub=!1}Rb=Ub?function(c,d){c.__proto__=d;if(c.__proto__!==d)throw new TypeError(c+" is not extensible");return c}:null}var Xb=Rb;Ob("Object.setPrototypeOf",function(c){return c||Xb});
(function(c){function d(a){for(var b=a[0],f=a[1],h,d,l=0,n=[];l<b.length;l++)d=b[l],k[d]&&n.push(k[d][0]),k[d]=0;for(h in f)Object.prototype.hasOwnProperty.call(f,h)&&(c[h]=f[h]);for(g&&g(a);n.length;)n.shift()()}function a(f){if(b[f])return b[f].exports;var e=b[f]={sg:f,vy:!1,exports:{}};c[f].call(e.exports,e,e.exports,a);e.vy=!0;return e.exports}var b={},k={4:0};a.e=function(b){var c=[],f=k[b];if(0!==f)if(f)c.push(f[2]);else{var g=new Promise(function(a,c){f=k[b]=[a,c]});c.push(f[2]=g);g=document.getElementsByTagName("head")[0];
var h=document.createElement("script");h.charset="utf-8";h.timeout=120;a.Ny&&h.setAttribute("nonce",a.Ny);h.src=a.p+""+({}[b]||b)+".js";var d=function(a){h.onerror=h.onload=null;clearTimeout(l);var c=k[b];if(0!==c){if(c){var f=a&&("load"===a.type?"missing":a.type);a=a&&a.target&&a.target.src;var e=Error("Loading chunk "+b+" failed.\n("+f+": "+a+")");e.type=f;e.request=a;c[1](e)}k[b]=void 0}};var l=setTimeout(function(){d({type:"timeout",target:h})},12E4);h.onerror=h.onload=d;g.appendChild(h)}return Promise.all(c)};
a.rE=c;a.VC=b;a.d=function(b,c,f){a.Qy(b,c)||Object.defineProperty(b,c,{enumerable:!0,get:f})};a.r=function(a){"undefined"!==typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})};a.t=function(b,c){c&1&&(b=a(b));if(c&8||c&4&&"object"===typeof b&&b&&b.__esModule)return b;var f=Object.create(null);a.r(f);Object.defineProperty(f,"default",{enumerable:!0,value:b});if(c&2&&"string"!=typeof b)for(var e in b)a.d(f,
e,function(a){return b[a]}.bind(null,e));return f};a.n=function(b){var c=b&&b.__esModule?function(){return b["default"]}:function(){return b};a.d(c,"a",c);return c};a.Qy=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};a.p="";a.vE=function(a){console.error(a);throw a;};var l=window.webpackJsonp=window.webpackJsonp||[],n=l.push.bind(l);l.push=d;l=l.slice();for(var f=0;f<l.length;f++)d(l[f]);var g=n;return a(a.QE=382)})({0:function(c,d){d.__esModule=!0;d.default=function(a,b){if(!(a instanceof
b))throw new TypeError("Cannot call a class as a function");}},124:function(c,d,a){var b=a(3)(b||{},{c:{nh:{}}});b.c.nh=function(){function a(){this.vu="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=window.crypto||window.msCrypto;b=window.Uint16Array&&b&&b.getRandomValues?b.getRandomValues(new Uint16Array(1))[0]%16:16*(Math.random()||0)%16;return("x"===a?b:b&3|8).toString(16)})}a.prototype.toString=function(){return this.vu};return a}();d.vdb={c:{nh:b.c.nh}};d.default=b.c.nh;
d.__esModule=!0},125:function(c,d){Object.defineProperty(d,"__esModule",{value:!0});d.Jk=function(a,b,c){return c?b+"dev/ad-client/js/"+c+"/":a+"ad-client/js/2.17.13/"}},3:function(c){c.exports=function a(){if(1>arguments.length||"object"!==typeof arguments[0])return!1;if(2>arguments.length)return arguments[0];var b=arguments[0],c,l,n,f;Array.prototype.slice.call(arguments,1).forEach(function(g){if("object"===typeof g)for(c in g)c in g&&(n=b[c],l=g[c],l!==b&&("object"!==typeof l||null===l?b[c]=l:
l instanceof Date?b[c]=new Date(l.getTime()):(f="object"!==typeof n||null===n?Array.isArray(l)?[]:{}:Array.isArray(l)?Array.isArray(n)?n:[]:Array.isArray(n)?{}:n,b[c]=a(f,l))))});return b}},35:function(c,d,a){var b=a(3)(b||{},{Ia:{}});b.Ia=function(){var a;return{M:function(c){var d="stage"===c,f=d?".dev":"",g=d?"-stage":"";a={"cdn.url":"https://cdn-ssl.vidible.tv/"+c+"/","s3.url":"https://s3.amazonaws.com/vdb-cdn-files/","tracking.url":"https://trk"+f+".vidible.tv/trk/","delivery.url":"https://delivery"+
f+".vidible.tv/","adserver.url":"https://video"+g+".adaptv.advertising.com/","adstracker.url":"https://video"+g+".adaptv.advertising.com/","aeg.default_vendor":d?"593fb37531e0a533fe6dd8fa":"593fb311c214e33ec50202f0","logger.level":d?"0":"3","ima.url":"https://s0.2mdn.net/instream/html5/ima3"+(d?"_debug":"")+".js","default.pid":d?"5912acc731e0a563e7535e52":"59947c0544a64b1a49e52a48","default.bid":d?"53a2cd08e4b0915a797d6a2e":"56bcd17de4b0a5976ac0da12","default.bcid":d?"50d595ec0364e95588c77bd2":"56bcd17ce4b018167fea5539"};
for(var h in a)Object.prototype.hasOwnProperty.call(a,h)&&(b.Ia[h]=a[h])}}}();d.vdb={Ia:b.Ia};d.default=b.Ia;d.__esModule=!0},375:function(c,d,a){Object.defineProperty(d,"__esModule",{value:!0});d.default=function(a){var c=a.queryString||"";a=k.default["tracking.url"]+"impression.gif?"+("pid="+(a.id||k.default["default.pid"])+"&")+("bcid="+(a.bcid||k.default["default.bcid"])+"&")+("s="+b.default.qe()+"&")+("pv="+(a.jsVersion||"2.17.13")+"&")+("ifr="+(window!==b.default.bf())+"&")+("cb="+Math.random()+
"&")+("pt="+a.playerType+"&")+("sid="+a.sid+"&")+("r="+encodeURIComponent(b.default.Fb()||"undefined"))+(-1!==c.indexOf("tbv=on")?"&itg=tbv":"");c=document.createElement("img");c.src=a;return c};var b=(c=a(73))&&c.__esModule?c:{default:c},k=(a=a(35))&&a.__esModule?a:{default:a}},381:function(c,d,a){Object.defineProperty(d,"__esModule",{value:!0});var b=(c=a(0))&&c.__esModule?c:{default:c},k=(a=a(375))&&a.__esModule?a:{default:a},l="startAd stopAd setAdVolume resizeAd pauseAd resumeAd expandAd collapseAd skipAd".split(" "),
n="getAdVolume getAdDuration getAdRemainingTime getAdExpanded getAdSkippableState getAdIcons getAdHeight getAdLinear getAdWidth".split(" ");a=function(){function a(c,f){function e(a){clearTimeout(d);this.d&&this.d("404");h&&(h.src=h.src.replace("impression","error")+"&dt=shim%20loading%3A%20"+a+"&et=ad&bid="+f.bid.id)}var g=this;(0,b.default)(this,a);var h=void 0;f.trackingEnabled&&(h=(0,k.default)(f));var d=setTimeout(e.bind(this,"timeout%2012s"),12E3);this.a=c.then(function(a){clearTimeout(d);return g.b=
a}).catch(e.bind(this,"not%20found"));this.tu(l);this.su(n)}a.prototype.tu=function(a){var b=this;a.forEach(function(a){b[a]=function(){for(var c=arguments.length,f=Array(c),e=0;e<c;e++)f[e]=arguments[e];b.a.then(function(b){return b[a].apply(b,f)})}})};a.prototype.su=function(a){var b=this;a.forEach(function(a){b[a]=function(){var c;return b.b&&(c=b.b)[a].apply(c,arguments)}})};a.prototype.initAd=function(a,b,c,f,d,k){this.a.then(function(e){return e.initAd(a,b,c,f,d,k)})};a.prototype.subscribe=
function(a,b,c){this.a.then(function(f){return f.subscribe(a,b,c)});"AdError"===b&&(this.d=a)};a.prototype.unsubscribe=function(a){this.a.then(function(b){return b.unsubscribe(a)})};a.prototype.handshakeVersion=function(a){return this.b&&this.b.handshakeVersion(a)||a};a.prototype.getAdCompanions=function(){return this.b&&this.b.getAdCompanions()||""};return a}();d.default=a},382:function(c,d,a){function b(a){return a&&a.__esModule?a:{default:a}}c=a(381);var k=b(c);c=a(125);d=a(124);var l=b(d);d=a(46);
var n=b(d);d=a(35);var f=b(d);d=a(69);var g=b(d),h=100;h=isNaN(h)?100:h;var e=!0,m={};try{m=JSON.parse(configSource),e=!1}catch(t){}var p=window.location.href,q=m.env||g.default.Eb("oathPlayerBuildEnvironment",p)||"stage";d="dev"===q;m.env=d?"stage":q;f.default.M(m.env);c=(0,c.Jk)(f.default["cdn.url"],f.default["s3.url"],g.default.Eb("oathPlayerBuildTag",p));a.p=d?"/build/":c;(function(a){a.bcid=a.bcid||f.default["default.bcid"];a.id=a.id||f.default["default.pid"];a.bid=a.bid||{};a.bid.id=a.bid.id||
f.default["default.bid"];a.sid=a.sid||(new l.default).toString();a.playerType=a.playerType||n.default.De;a.timestamp=+new Date;a.trackingEnabled=e||h>=Math.floor(101*Math.random())})(m);var r=a.e(0).then(a.t.bind(null,383,7)).then(function(a){return a.default(m)});window.getVPAIDAd=function(){return new k.default(r,m)}},46:function(c,d,a){var b=a(3)(b||{},{f:{dd:{}}});b.f.dd={If:"flash",Ks:"html5",De:"o2unit",BB:"VRM_plgn",cC:"smart",Dt:"VDMS"};d.vdb={f:{dd:b.f.dd}};d.default=b.f.dd;d.__esModule=
!0},69:function(c,d,a){var b=a(3)(b||{},{c:{hd:{}}});b.c.hd=function(){return{Eb:function(a,b){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec(b);return null==a?"":decodeURIComponent(a[1].replace(/\+/g," "))}}}();d.vdb={c:{hd:b.c.hd}};d.default=b.c.hd;d.__esModule=!0},73:function(c,d,a){var b=a(3)(b||{},{c:{Kb:{}}});b.c.Kb=function(a){return{Fb:function(b){var c=b||a;b=this.bf(c);c=c&&c.location&&c.location.ancestorOrigins;return b===a.top?b.location.href:
c&&1<c.length?c[c.length-1]:b.document&&b.document.referrer||b.location.href},bf:function(b){for(b=b||a;b;)try{var c=b.parent;if(!c.document)break;b=c;if(c===c.parent)break}catch(f){break}return b},Bi:function(b){b=b||a;try{return b.parent}catch(n){}return null},qe:function(){return-1===(a.location.protocol||this.Fb()||"").indexOf("http:")}}}(window);d.vdb={c:{Kb:b.c.Kb}};d.default=b.c.Kb;d.__esModule=!0}});}).call(this, '{"jsVersion":"2.17.13","flashVersion":"17.06.352","id":"59947c0544a64b1a49e52a48","bid":{"id":"56bcd17de4b0a5976ac0da12"},"ts":"20180627013642098","adSettings":{"podSize":1,"prerollInterleave":1,"hardTimeout":7.0,"strictSiteCheckForAds":false,"blockContentOnAdBlocker":false, "domainOptimisation":true,"adStrategy":"ADSET_BASED","useSsai":false,"companions":[{"width":300,"height":250,"parent":"companion1", "keepCompanion":false,"failoverOnStart":false},{"width":300,"height":100,"parent":"companion2","keepCompanion":false,"failoverOnStart":false}, {"width":728,"height":90,"parent":"companion3","keepCompanion":false,"failoverOnStart":false}],"aeg":[],"asids":[]},"sid":"622f24ac-d177-43f7-b886-adb07f60794b","env":"prod","bcid":"5909e6837cdce053ec937c7f","playerTemplate":{"metaData":{}},"queryString":"companionId=&cpmPassback=&placementId=834008&orgId=7060&injectCompanionDummy=&pauseOnClick=&d.vw=&d.app=&r=http%3A%2F%2Fwww.edivaldobrito.com.br%2Fcomo-agendar-um-desligamento-linux%2F","isEU":false}')
