(function(g){var window=this;var ZAa=function(a,b){return g.Sb(a,b)},M6=function(a){g.Bm(a,"zx",g.wb());
return a},N6=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Em(a.g,b,c)},$Aa=function(a,b){var c=[];
g.nk(b,function(a){try{var b=g.aD.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.$C(b)&&c.push(a):c.push(a)},a);
return c},aBa=function(a,b){var c=$Aa(a,b);
(0,g.B)(c,function(a){g.aD.prototype.remove.call(this,a)},a)},bBa=function(a){if(a.yd){if(a.yd.locationOverrideToken)return{locationOverrideToken:a.yd.locationOverrideToken};
if(null!=a.yd.latitudeE7&&null!=a.yd.longitudeE7)return{latitudeE7:a.yd.latitudeE7,longitudeE7:a.yd.longitudeE7}}return null},cBa=function(a,b,c,d){var e=new g.sm(null,void 0);
a&&g.tm(e,a);b&&g.um(e,b);c&&g.vm(e,c);d&&g.wm(e,d);return e},dBa=function(a){g.QF[a]&&(a=g.QF[a],(0,g.B)(a,function(a){g.OF[a]&&delete g.OF[a]}),a.length=0)},eBa=function(a){var b=g.NF();
if(b)if(b.clear(a),a)dBa(a);else for(var c in g.QF)dBa(c)},O6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.mm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",fBa(this,a.capabilities||""),gBa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},fBa=function(a,b){a.capabilities.clear();
(0,g.Jd)(b.split(","),g.Fa(ZAa,hBa)).forEach(function(b){a.capabilities.add(b)})},gBa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},P6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},Q6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},iBa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},jBa=function(a){return new P6(a)},kBa=function(a){return g.za(a)?(0,g.G)(a,jBa):[]},R6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},S6=function(a){return g.za(a)?"["+(0,g.G)(a,R6).join(",")+"]":"null"},T6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},lBa=function(a){return(0,g.G)(a,function(a){return{key:a.id,
name:a.name}})},U6=function(a,b){return g.Ka(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},V6=function(a,b){return g.Ka(a,function(a){return Q6(a,b)})},mBa=function(){var a=(0,g.JG)();
a&&aBa(a,a.g.Qd(!0))},W6=function(){var a=g.MG("yt-remote-connected-devices")||[];
g.fb(a);return a},nBa=function(a){if(g.Pa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(a,b){return 0==b?a:a.substring(c.length)})},oBa=function(a){g.LG("yt-remote-connected-devices",a,86400)},Y6=function(){if(X6)return X6;
var a=g.MG("yt-remote-device-id");a||(a=T6(),g.LG("yt-remote-device-id",a,31536E3));for(var b=W6(),c=1,d=a;g.Oa(b,d);)c++,d=a+"#"+c;return X6=d},Z6=function(){var a=W6(),b=Y6();
g.Oa(a,b);g.OG()&&g.ib(a,b);a=nBa(a);if(g.Pa(a))try{g.wG("remote_sid")}catch(c){}else try{g.vG("remote_sid",a.join(","),-1)}catch(c){}},pBa=function(){return g.MG("yt-remote-session-browser-channel")},qBa=function(){return g.MG("yt-remote-local-screens")||[]},rBa=function(){g.LG("yt-remote-lounge-token-expiration",!0,86400)},sBa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(qBa(),function(a){return a.loungeToken}),c=(0,g.G)(a,function(a){return a.loungeToken});
(0,g.am)(c,function(a){return!g.Oa(b,a)})&&rBa();
g.LG("yt-remote-local-screens",a,31536E3)},tBa=function(a,b){g.LG("yt-remote-session-browser-channel",a);
g.LG("yt-remote-session-screen-id",b);var c=W6(),d=Y6();g.Oa(c,d)||c.push(d);oBa(c);Z6()},$6=function(a){a||(g.NG("yt-remote-session-screen-id"),g.NG("yt-remote-session-video-id"));
Z6();a=W6();g.Ta(a,Y6());oBa(a)},uBa=function(){if(!a7){var a=g.lD();
a&&(a7=new g.VC(a))}return a7?!!a7.get("yt-remote-use-staging-server"):!1},vBa=function(){var a=window.document.createElement("a");
g.Yc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ab(a)},wBa=function(a,b){var c=g.Cd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.$c(c,g.ae("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},xBa=function(){var a=vBa(),b=window.document.getElementById(a),c=b&&g.ZE(b,"loaded");
c||b&&!c||(b=wBa(a,function(){g.ZE(b,"loaded")||(g.YE(b,"loaded","true"),g.UF(a),g.UD(g.Fa(eBa,a),0))}))},b7=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},yBa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},c7=function(a){a.length?zBa(a.shift(),function(){c7(a)}):d7()},ABa=function(a){return"chrome-extension://"+a+e7},zBa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},f7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},d7=function(){var a=yBa();
a&&a(!1,"No cast extension found")},g7=function(){if(BBa){var a=2,b=yBa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;zBa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",d7,c)}},CBa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(g7(),a({command:"cast.sender.init"}))},DBa=function(){g7();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);c7(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+e7,"//www.gstatic.com/eureka/clank"+e7])},h7=function(a,b,c){g.M.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.pd=b;this.B=(0,g.z)(this.MJ,this);this.g=!1;this.l=0;this.o=this.Ba=null;this.A=[]},i7=function(){},j7=function(a,b,c,d){this.g=a;
this.o=b;this.D=c;this.C=d||1;this.A=45E3;this.W=new g.Im(this);this.l=new g.qg;this.l.setInterval(250)},FBa=function(a,b,c){a.Kj=1;
a.mh=M6(b.clone());a.Ri=c;a.B=!0;EBa(a,null)},k7=function(a,b,c,d,e){a.Kj=1;
a.mh=M6(b.clone());a.Ri=null;a.B=c;e&&(a.fE=!1);EBa(a,d)},EBa=function(a,b){a.zk=(0,g.F)();
l7(a);a.Jh=a.mh.clone();N6(a.Jh,"t",a.C);a.Sm=0;a.Qc=a.g.Rr(a.g.Im()?b:null);0<a.Gs&&(a.Pp=new g.Rk((0,g.z)(a.wF,a,a.Qc),a.Gs));a.W.U(a.Qc,"readystatechange",a.iV);var c=a.mi?g.$b(a.mi):{};a.Ri?(a.Dq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Qc.send(a.Jh,a.Dq,a.Ri,c)):(a.Dq="GET",a.fE&&!g.yd&&(c.Connection="close"),a.Qc.send(a.Jh,a.Dq,null,c));a.g.Af(1)},IBa=function(a,b,c){for(var d=!0;!a.Wh&&a.Sm<c.length;){var e=GBa(a,c);
if(e==m7){4==b&&(a.nh=4,n7(15),d=!1);break}else if(e==HBa){a.nh=4;n7(16);d=!1;break}else o7(a,e)}4==b&&0==c.length&&(a.nh=1,n7(17),d=!1);a.Gf=a.Gf&&d;d||(p7(a),q7(a))},GBa=function(a,b){var c=a.Sm,d=b.indexOf("\n",c);
if(-1==d)return m7;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return HBa;d+=1;if(d+c>b.length)return m7;var e=b.substr(d,c);a.Sm=d+c;return e},KBa=function(a,b){a.zk=(0,g.F)();
l7(a);var c=b?window.location.hostname:"";a.Jh=a.mh.clone();g.Bm(a.Jh,"DOMAIN",c);g.Bm(a.Jh,"t",a.C);try{a.Hf=new window.ActiveXObject("htmlfile")}catch(n){p7(a);a.nh=7;n7(22);q7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in r7)k=r7[l];else if(l in JBa)k=r7[l]=JBa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=r7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.ad(g.tc("b/12014412"),d);a.Hf.open();a.Hf.write(g.Sc(c));a.Hf.close();a.Hf.parentWindow.m=(0,g.z)(a.rU,a);a.Hf.parentWindow.d=(0,g.z)(a.pD,a,!0);a.Hf.parentWindow.rpcClose=(0,g.z)(a.pD,a,!1);c=a.Hf.createElement("DIV");a.Hf.parentWindow.document.body.appendChild(c);d=g.Jc(a.Jh.toString());d=g.pb(g.Gc(d));d=g.ad(g.tc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Sc(d);
a.g.Af(1)},l7=function(a){a.kw=(0,g.F)()+a.A;
LBa(a,a.A)},LBa=function(a,b){if(null!=a.Pk)throw Error("WatchDog timer not null");
a.Pk=s7((0,g.z)(a.HU,a),b)},t7=function(a){a.Pk&&(g.w.clearTimeout(a.Pk),a.Pk=null)},q7=function(a){a.g.yz()||a.Wh||a.g.Bp(a)},p7=function(a){t7(a);
g.Ze(a.Pp);a.Pp=null;a.l.stop();g.Om(a.W);if(a.Qc){var b=a.Qc;a.Qc=null;b.abort();b.dispose()}a.Hf&&(a.Hf=null)},o7=function(a,b){try{a.g.iD(a,b),a.g.Af(4)}catch(c){}},NBa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;MBa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){NBa(a,b,c,d,f)},f)})}},MBa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{u7(d),c(!0)}catch(e){}};
d.onerror=function(){try{u7(d),c(!1)}catch(e){}};
d.onabort=function(){try{u7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{u7(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},u7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},OBa=function(a){this.g=a;
this.l=new i7},PBa=function(a){var b=v7(a.g,a.Zk,"/mail/images/cleardot.gif");
M6(b);NBa(b.toString(),5E3,(0,g.z)(a.ZI,a),3,2E3);a.Af(1)},x7=function(a){var b=a.g.H;
if(null!=b)n7(5),b?(n7(11),w7(a.g,a,!1)):(n7(12),w7(a.g,a,!0));else if(a.te=new j7(a,void 0,void 0,void 0),a.te.mi=a.Es,b=a.g,b=v7(b,b.Im()?a.El:null,a.Fs),n7(5),!g.wd||g.pc(10))N6(b,"TYPE","xmlhttp"),k7(a.te,b,!1,a.El,!1);else{N6(b,"TYPE","html");var c=a.te;a=!!a.El;c.Kj=3;c.mh=M6(b.clone());KBa(c,a)}},y7=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new i7;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},QBa=function(a,b){this.g=a;
this.map=b;this.context=null},RBa=function(a){g.af.call(this,"statevent",a)},SBa=function(a,b){g.af.call(this,"timingevent",a);
this.size=b},TBa=function(a){g.af.call(this,"serverreachability",a)},WBa=function(a){UBa(a);
if(3==a.g){var b=a.pm++,c=a.lo.clone();g.Bm(c,"SID",a.o);g.Bm(c,"RID",b);g.Bm(c,"TYPE","terminate");z7(a,c);b=new j7(a,a.o,b,void 0);b.Kj=2;b.mh=M6(c.clone());(new window.Image).src=b.mh;b.zk=(0,g.F)();l7(b)}VBa(a)},XBa=function(a){a.uJ(1,0);
a.lo=v7(a,null,a.Ds);A7(a)},UBa=function(a){a.ah&&(a.ah.abort(),a.ah=null);
a.tc&&(a.tc.cancel(),a.tc=null);a.sg&&(g.w.clearTimeout(a.sg),a.sg=null);B7(a);a.Wd&&(a.Wd.cancel(),a.Wd=null);a.eh&&(g.w.clearTimeout(a.eh),a.eh=null)},YBa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new QBa(a.bQ++,b));2!=a.g&&3!=a.g||A7(a)},A7=function(a){a.Wd||a.eh||(a.eh=s7((0,g.z)(a.nD,a),0),a.zj=0)},$Ba=function(a,b){if(1==a.g){if(!b){a.pm=Math.floor(1E5*Math.random());
var c=a.pm++,d=new j7(a,"",c,void 0);d.mi=null;var e=C7(a),f=a.lo.clone();g.Bm(f,"RID",c);g.Bm(f,"CVER","1");z7(a,f);FBa(d,f,e);a.Wd=d;a.g=2}}else 3==a.g&&(b?ZBa(a,b):0==a.l.length||a.Wd||ZBa(a))},ZBa=function(a,b){if(b)if(6<a.Yh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.pm-1;var d=C7(a)}else c=b.D,d=b.Ri;else c=a.pm++,d=C7(a);var e=a.lo.clone();g.Bm(e,"SID",a.o);g.Bm(e,"RID",c);g.Bm(e,"AID",a.Yj);z7(a,e);c=new j7(a,a.o,c,a.zj+1);c.mi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Wd=c;FBa(c,e,d)},z7=function(a,b){if(a.od){var c=a.od.dz();
c&&g.Ib(c,function(a,c){g.Bm(b,c,a)})}},C7=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Yh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Yh?e:f-d;try{g.Ib(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},aCa=function(a){a.tc||a.sg||(a.D=1,a.sg=s7((0,g.z)(a.mD,a),0),a.mj=0)},D7=function(a){if(a.tc||a.sg||3<=a.mj)return!1;
a.D++;a.sg=s7((0,g.z)(a.mD,a),bCa(a,a.mj));a.mj++;return!0},w7=function(a,b,c){a.Cq=c;
a.Uf=b.Dg;a.C||XBa(a)},B7=function(a){null!=a.bi&&(g.w.clearTimeout(a.bi),a.bi=null)},bCa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},E7=function(a,b){if(2==b||9==b){var c=null;
a.od&&(c=null);var d=(0,g.z)(a.aW,a);c||(c=new g.sm("//www.google.com/images/cleardot.gif"),M6(c));MBa(c.toString(),1E4,d)}else n7(2);cCa(a,b)},cCa=function(a,b){a.g=0;
a.od&&a.od.Vx(b);VBa(a);UBa(a)},VBa=function(a){a.g=0;
a.Uf=-1;if(a.od)if(0==a.A.length&&0==a.l.length)a.od.Er();else{g.Wa(a.A);var b=g.Wa(a.l);a.A.length=0;a.l.length=0;a.od.Er(b)}},v7=function(a,b,c){var d=g.Cm(c);
if(""!=d.l)b&&g.um(d,b+"."+d.l),g.vm(d,d.B);else{var e=window.location;d=cBa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.ql&&g.Ib(a.ql,function(a,b){g.Bm(d,b,a)});
g.Bm(d,"VER",a.Yh);z7(a,d);return d},s7=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},n7=function(a){F7.dispatchEvent(new RBa(F7,a))},dCa=function(){},eCa=function(a,b){this.action=a;
this.params=b||{}},G7=function(a,b){g.M.call(this);
this.g=new g.Wt(this.iU,0,this);g.N(this,this.g);this.pd=5E3;this.l=0;if(g.Ba(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},H7=function(a,b,c){this.J=a;
this.C=b;this.o=new g.UC;this.l=new G7(this.JW,this);this.g=this.Ya=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.K=c||!1},fCa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Cq,sessionId:a.g.o,arrayId:a.g.Yj}},gCa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&$Ba(a.g),WBa(a.g));a.F=0},I7=function(a){return!!a.g&&3==a.g.g},hCa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},J7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Gg(a)||"";b&&(this.port=":"+b);this.domain=g.Fg(a)||"";a=g.Gb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.zb(a,"10.0")&&(this.l=!1))},K7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Pg(c+b,{})},L7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Fa(a.A,d,!0),onError:g.Fa(a.o,e),ud:g.Fa(a.B,e)};c&&(a.Mb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.kE(b,a)},lCa=function(){var a=iCa;
jCa();M7.push(a);kCa(M7)},N7=function(a,b){jCa();
var c=M7,d=mCa(a,String(b));g.Pa(c)?nCa(d):(kCa(c),(0,g.B)(c,function(a){a(d)}))},jCa=function(){M7||(M7=g.x("yt.mdx.remote.debug.handlers_")||[],g.wa("yt.mdx.remote.debug.handlers_",M7,void 0))},nCa=function(a){var b=(O7+1)%50;
O7=b;P7[b]=a;Q7||(Q7=49==b)},kCa=function(a){var b=P7;
if(b[0]){var c=O7,d=Q7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(a){a(e)})}while(d!=c);
P7=Array(50);O7=-1;Q7=!1}},mCa=function(a,b){var c=((0,g.F)()-oCa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},R7=function(a){g.FF.call(this);
this.D=a;this.g=[]},pCa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},qCa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Jd)(a.g,function(a){return!!U6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=pCa(a,b[d])||c;return c},rCa=function(a,b){var c=a.g.length;
a.g=(0,g.Jd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},S7=function(a,b,c,d){g.FF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.Ba=window.NaN},U7=function(a){R7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;T7(this);this.info("Initializing with "+S6(this.g))},sCa=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(a){return a.id}),c=K7(a.o,"/pairing/get_lounge_token_batch");
L7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.ZJ,a),(0,g.z)(a.YJ,a))}},T7=function(a){var b=kBa(qBa());
b=(0,g.Jd)(b,function(a){return!a.uuid});
return qCa(a,b)},V7=function(a,b){sBa((0,g.G)(a.g,iBa));
b&&rBa()},X7=function(a,b){g.FF.call(this);
this.C=b;var c=g.MG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Oa(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;W7("Initialized with "+g.xg(this.g))},tCa=function(a,b,c){var d=K7(a.B,"/pairing/get_screen_availability");
L7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},Y7=function(a,b){a:if(g.Mb(b)!=g.Mb(a.g))var c=!1;
else{c=g.Pb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(W7("Updated online screens: "+g.xg(a.g)),a.g=b,a.R("screenChange"));uCa(a)},Z7=function(a){(0,window.isNaN)(a.o)||g.WD(a.o);
a.o=g.UD((0,g.z)(a.Av,a),0<a.A&&a.A<(0,g.F)()?2E4:1E4)},W7=function(a){N7("OnlineScreenService",a)},vCa=function(a){var b={};
(0,g.B)(a.C(),function(a){a.token?b[a.token]=a.id:this.fc("Requesting availability of screen w/o lounge token.")});
return b},uCa=function(a){a=g.Pb(g.Jb(a.g,function(a){return a}));
g.fb(a);a.length?g.LG("yt-remote-online-screen-ids",a.join(","),60):g.NG("yt-remote-online-screen-ids")},$7=function(a){R7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};wCa(this)},yCa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ke();if(k=(c?V6(k,c):null)||V6(k,b)){k.uuid=b;var l=a8(a,k);tCa(a.l,l,function(a){e(a?l:null)})}else c?xCa(a,c,(0,g.z)(function(a){var f=a8(this,new P6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));tCa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},zCa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},xCa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Mb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.kE(K7(a.C,"/pairing/get_lounge_token_batch"),e)},ACa=function(a){a.g=a.o.ke();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+S6(a.g))},wCa=function(a){b8(a);
a.o=new U7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.oK,a));ACa(a);a.A=kBa(g.MG("yt-remote-automatic-screen-cache")||[]);b8(a);a.info("Initializing automatic screens: "+S6(a.A));a.l=new X7(a.C,(0,g.z)(a.ke,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.R("onlineScreenChange")},a))},a8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=V6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.LG("yt-remote-automatic-screen-cache",(0,g.G)(a.A,iBa)));b8(a);a.B[b.uuid]=b.id;g.LG("yt-remote-device-id-map",a.B,31536E3);return b},b8=function(a){a.B=g.MG("yt-remote-device-id-map")||{}},c8=function(a,b,c){g.FF.call(this);
this.K=c;this.H=a;this.l=b;this.o=null},d8=function(a,b){N7(a.K,b)},e8=function(a,b){c8.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.PW,this);this.B=(0,g.z)(this.TU,this);this.A=g.UD((0,g.z)(function(){BCa(this,null)},this),12E4)},CCa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.xg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){d8(this,"Failed to send message: getMdxSessionStatus.")},a)):d8(a,"Sending yt message without session: "+g.xg(b))},BCa=function(a,b){g.WD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.Cp,a),d=(0,g.z)(a.re,a);a.nz(b,c,d,5)}}else a.re(Error("Waiting for session status timed out."))},f8=function(a,b,c){c8.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.M=c;this.B=null;this.D=g.y;this.C=window.NaN;this.J=(0,g.z)(this.SW,this);this.g=g.y},DCa=function(a){a.g=a.H.DF(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Cp(a)},a),(0,g.z)(function(a){this.g=g.y;
this.re(a)},a))},ECa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.M;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}uBa()&&(b.env_useStageMdx=1);return g.Ng(b)},g8=function(a,b){c8.call(this,a,b,"ManualSession");
this.g=g.UD((0,g.z)(this.ak,this,null),150)},h8=function(a,b,c,d){g.FF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.rT,this)},FCa=function(a,b){return b?g.Ka(a.o,function(a){return Q6(b,a.label)},a):null},i8=function(a){N7("Controller",a)},iCa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},j8=function(a){return a.B||!!a.o.length||!!a.g},k8=function(a,b,c){b!=a.g&&(g.Ze(a.g),(a.g=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.l):a.R("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.kD,a,b)),b.o?a.R("yt-remote-cast2-session-change",b.o):c&&a.g.ak(null)):a.R("yt-remote-cast2-session-change",null))},GCa=function(a){var b=a.l.CF(),c=a.g&&a.g.l;
a=(0,g.G)(b,function(a){c&&Q6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=FCa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},MCa=function(a,b,c,d,e,f,k){HCa()?ICa(b,e,f,k)&&(m8(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?JCa(a,c):(window.__onGCastApiAvailable=function(b,d){b?JCa(a,c):(n8("Failed to load cast API: "+d),o8(!1),m8(!1),g.NG("yt-remote-cast-available"),g.NG("yt-remote-cast-receiver"),KCa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):xBa():f7("CriOS")?CBa():f7("Android")&&f7("Chrome/")&&window.navigator.presentation?DBa():window.chrome&&window.navigator.presentation&&!f7("Edge")?(g7(),c7(LCa.map(ABa))):d7())):l8("Cannot initialize because not running Chrome")},KCa=function(){l8("dispose");
var a=p8();a&&a.dispose();g.wa("yt.mdx.remote.cloudview.instance_",null,void 0);NCa(!1);g.SF(q8);q8.length=0},r8=function(){return!!g.MG("yt-remote-cast-installed")},OCa=function(){var a=g.MG("yt-remote-cast-receiver");
return a?a.friendlyName:null},PCa=function(){l8("clearCurrentReceiver");
g.NG("yt-remote-cast-receiver")},QCa=function(){return r8()?p8()?p8().getCastSession():(n8("getCastSelector: Cast is not initialized."),null):(n8("getCastSelector: Cast API is not installed!"),null)},t8=function(){r8()?p8()?s8()?(l8("Requesting cast selector."),p8().requestSession()):(l8("Wait for cast API to be ready to request the session."),q8.push(g.RF("yt-remote-cast2-api-ready",t8))):n8("requestCastSelector: Cast is not initialized."):n8("requestCastSelector: Cast API is not installed!")},u8=
function(a,b){s8()?p8().setConnectedScreenStatus(a,b):n8("setConnectedScreenStatus called before ready.")},HCa=function(){var a=0<=g.Gb.search(/ (CrMo|Chrome|CriOS)\//);
return g.xI||a},RCa=function(a,b){p8().init(a,b)},ICa=function(a,b,c,d){var e=!1;
p8()||(a=new h8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.LG("yt-remote-cast-available",a);g.VF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){l8("onReceiverSelected: "+a.friendlyName);
g.LG("yt-remote-cast-receiver",a);g.VF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){l8("onReceiverResumed: "+a.friendlyName);
g.LG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){l8("onSessionChange: "+R6(a));
a||g.NG("yt-remote-cast-receiver");g.VF("yt-remote-cast2-session-change",a)}),g.wa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
l8("cloudview.createSingleton_: "+e);return e},p8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},JCa=function(a,b){o8(!0);
m8(!1);RCa(a,function(a){a?(NCa(!0),g.UF("yt-remote-cast2-api-ready")):(n8("Failed to initialize cast API."),o8(!1),g.NG("yt-remote-cast-available"),g.NG("yt-remote-cast-receiver"),KCa());b(a)})},l8=function(a){N7("cloudview",a)},n8=function(a){N7("cloudview",a)},o8=function(a){l8("setCastInstalled_ "+a);
g.LG("yt-remote-cast-installed",a)},s8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},NCa=function(a){l8("setApiReady_ "+a);
g.wa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},m8=function(a){g.wa("yt.mdx.remote.cloudview.initializing_",a,void 0)},v8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Xf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},w8=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Xf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.F)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},x8=function(a){return a.kb()?((0,g.F)()-a.D)/1E3:0},y8=function(a,b){a.F=b;
a.D=(0,g.F)()},z8=function(a){switch(a.g){case 1:case 1081:return((0,g.F)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},A8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&w8(a)},B8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ac(a.l);b.hasPrevious=a.Xf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},D8=function(a,b){g.FF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.kC;this.o=this.l=null;this.H=(0,g.z)(this.LQ,this);this.D=(0,g.z)(this.sm,this);this.F=(0,g.z)(this.KQ,this);this.I=(0,g.z)(this.XQ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.tw,this),SCa(this))):c=3;0!=c&&(b?this.tw(c):g.UD((0,g.z)(function(){this.tw(c)},this),0));
var d=QCa();d&&C8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},E8=function(a){return new v8(a.A.getPlayerContextData())},SCa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Fa(this.mT,a),this))},a)},TCa=function(a){(0,g.B)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},F8=function(a,b){50>a.B.Cc()&&g.mC(a.B,b)},H8=function(a,b,c){var d=E8(a);
y8(d,c);-1E3!=d.g&&(d.g=b);G8(a,d)},I8=function(a,b,c){a.A.sendMessage(b,c)},G8=function(a,b){TCa(a);
a.A.setPlayerContextData(B8(b));SCa(a)},C8=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.sm(null));
a.o=b;a.o&&(N7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.sm(a.o.media[0]))},UCa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=E8(a);b.contentId!=d.videoId&&N7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;y8(d,a.l.getEstimatedTime());G8(a,d)}else N7("CP","No cast media video. Ignoring state update.")},J8=function(a,b,c){return(0,g.z)(function(a){this.fc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.fc("Retrying "+b+" using MDx browser channel."),I8(this,b,c))},a)},K8=function(a,b,c){g.FF.call(this);
this.B=window.NaN;this.M=!1;this.I=this.H=this.J=this.K=window.NaN;this.T=[];this.A=this.D=this.o=this.Za=this.g=null;this.ra=a;this.T.push(g.oF(window,"beforeunload",(0,g.z)(this.QJ,this)));this.l=[];this.Za=new v8;this.Z=b.id;this.g=VCa(this,c);this.g.subscribe("handlerOpened",this.PQ,this);this.g.subscribe("handlerClosed",this.MQ,this);this.g.subscribe("handlerError",this.NQ,this);this.g.subscribe("handlerMessage",this.OQ,this);hCa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Za.videoId;g.OG()&&g.LG("yt-remote-session-video-id",a)},this)},L8=function(a){N7("conn",a)},VCa=function(a,b){return new H7(K7(a.ra,"/bc"),b)},M8=function(a,b){a.R("proxyStateChange",b)},WCa=function(a){a.B=g.UD((0,g.z)(function(){L8("Connecting timeout");
this.C(1)},a),2E4)},N8=function(a){g.WD(a.B);
a.B=window.NaN},O8=function(a){g.WD(a.K);
a.K=window.NaN},XCa=function(a){P8(a);
a.J=g.UD((0,g.z)(function(){Q8(this,"getNowPlaying")},a),2E4)},P8=function(a){g.WD(a.J);
a.J=window.NaN},ZCa=function(a,b){b&&(N8(a),O8(a));
b==(I7(a.g)&&(0,window.isNaN)(a.B))?b&&(M8(a,1),Q8(a,"getSubtitlesTrack")):b?(a.X()&&a.Za.reset(),M8(a,1),Q8(a,"getNowPlaying"),YCa(a)):a.C(1)},$Ca=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Za.videoId&&(g.Vb(b.params)?a.Za.l=null:a.Za.l=b.params,a.R("remotePlayerChange"))},aDa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Za.listId=b.params.listId||a.Za.listId;A8(a.Za,c,d);a.R("remoteQueueChange")},cDa=function(a,b){b.params=b.params||{};
aDa(a,b);bDa(a,b);a.R("autoplayDismissed")},bDa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
y8(a.Za,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Za.g&&(c=-1E3);a.Za.g=c;c=Number(b.params.loadedTime);a.Za.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Za.H=(0,window.isNaN)(c)?0:c;c=a.Za;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Za;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Za.g?XCa(a):P8(a);
a.R("remotePlayerChange")},dDa=function(a,b){if(-1E3!=a.Za.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Za.g=c;c=(0,window.parseInt)(b.params.currentTime,10);y8(a.Za,(0,window.isNaN)(c)?0:c);a.R("remotePlayerChange")}},eDa=function(a,b){var c="true"==b.params.muted;
a.Za.volume=(0,window.parseInt)(b.params.volume,10);a.Za.muted=c;a.R("remotePlayerChange")},fDa=function(a,b){a.D=b.params.videoId;
a.R("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},gDa=function(a,b){var c="true"==b.params.hasNext;
a.Za.Xf="true"==b.params.hasPrevious;a.Za.hasNext=c;a.R("previousNextChange")},YCa=function(a){g.WD(a.I);
a.I=g.UD((0,g.z)(a.C,a,1),864E5)},Q8=function(a,b,c){c?L8("Sending: action="+b+", params="+g.xg(c)):L8("Sending: action="+b);
a.g.sendMessage(b,c)},R8=function(a){R7.call(this,"ScreenServiceProxy");
this.ed=a;this.l=[];this.l.push(this.ed.$_s("screenChange",(0,g.z)(this.NW,this)));this.l.push(this.ed.$_s("onlineScreenChange",(0,g.z)(this.NS,this)))},lDa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.OD("MDX_CONFIG")||b;mBa();Z6();S8||(S8=new J7(b?b.loungeApiHost:void 0),uBa()&&(S8.g="/api/loungedev"));T8||(T8=g.x("yt.mdx.remote.deferredProxies_")||[],g.wa("yt.mdx.remote.deferredProxies_",T8,void 0));hDa();var c=U8();if(!c){var d=new $7(S8);g.wa("yt.mdx.remote.screenService_",d,void 0);c=U8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);MCa(a,d,function(a){a?V8()&&u8(V8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.VF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.wa("yt.mdx.remote.initialized_",!0,void 0),W8("Initializing: "+g.xg(b)),X8.push(g.RF("yt-remote-cast2-availability-change",function(){g.VF("yt-remote-receiver-availability-change")})),X8.push(g.RF("yt-remote-cast2-receiver-selected",function(){Y8(null);
g.VF("yt-remote-auto-connect","cast-selector-receiver")})),X8.push(g.RF("yt-remote-cast2-receiver-resumed",function(){g.VF("yt-remote-receiver-resumed","cast-selector-receiver")})),X8.push(g.RF("yt-remote-cast2-session-change",iDa)),X8.push(g.RF("yt-remote-connection-change",function(a){a?u8(V8(),"YouTube TV"):Z8()||(u8(null,null),PCa())})),a=$8(),b.isAuto&&(a.id+="#dial"),g.LF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),W8(" -- with channel params: "+
g.xg(a)),jDa(a),c.start(),V8()||kDa())},nDa=function(){var a=mDa();
r8()&&g.MG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},mDa=function(){var a=U8().ed.$_gos();
var b=a9();b&&b9()&&(U6(a,b)||a.push(b));return lBa(a)},c9=function(){var a=oDa();
!a&&r8()&&OCa()&&(a={key:"cast-selector-receiver",name:OCa()});return a},oDa=function(){var a=mDa(),b=a9();
b||(b=Z8());return g.Ka(a,function(a){return b&&Q6(b,a.key)?!0:!1})},a9=function(){var a=V8();
if(!a)return null;var b=U8().ke();return V6(b,a)},iDa=function(a){W8("remote.onCastSessionChange_: "+R6(a));
if(a){var b=a9();b&&b.id==a.id?u8(b.id,"YouTube TV"):(b&&d9(),e9(a,1))}else b9()&&d9()},d9=function(){s8()?p8().stopSession():n8("stopSession called before API ready.");
var a=b9();a&&(a.disconnect(1),f9(null))},g9=function(){var a=b9();
return!!a&&3!=a.getProxyState()},W8=function(a){N7("remote",a)},U8=function(){if(!h9){var a=g.x("yt.mdx.remote.screenService_");
h9=a?new R8(a):null}return h9},V8=function(){return g.x("yt.mdx.remote.currentScreenId_")},pDa=function(a){g.wa("yt.mdx.remote.currentScreenId_",a,void 0)},qDa=function(){return g.x("yt.mdx.remote.connectData_")},Y8=function(a){g.wa("yt.mdx.remote.connectData_",a,void 0)},b9=function(){return g.x("yt.mdx.remote.connection_")},f9=function(a){var b=b9();
Y8(null);a||pDa("");g.wa("yt.mdx.remote.connection_",a,void 0);T8&&((0,g.B)(T8,function(b){b(a)}),T8.length=0);
b&&!a?g.VF("yt-remote-connection-change",!1):!b&&a&&g.VF("yt-remote-connection-change",!0)},Z8=function(){var a=g.OG();
if(!a)return null;var b=U8().ke();return V6(b,a)},e9=function(a,b){a9()&&a9();
pDa(a.id);var c=new K8(S8,a,$8());c.connect(b,qDa());c.subscribe("beforeDisconnect",function(a){g.VF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){b9()&&f9(null)});
f9(c)},kDa=function(){var a=Z8();
a?(W8("Resume connection to: "+R6(a)),e9(a,0)):($6(),PCa(),W8("Skipping connecting because no session screen found."))},hDa=function(){var a=$8();
if(g.Vb(a)){a=Y6();var b=g.MG("yt-remote-session-name")||"",c=g.MG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.wa("yt.mdx.remote.channelParams_",a,void 0)}},$8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},jDa=function(a){a?(g.LG("yt-remote-session-app",a.app),g.LG("yt-remote-session-name",a.name)):(g.NG("yt-remote-session-app"),g.NG("yt-remote-session-name"));
g.wa("yt.mdx.remote.channelParams_",a,void 0)},i9=function(a,b,c){g.M.call(this);
this.F=a;this.l=b;this.o=new g.CF(this);g.N(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.eS);this.o.O(b,"captionschanged",this.JQ);this.o.O(b,"captionssettingschanged",this.QE);this.o.O(b,"videoplayerreset",this.Dp);this.o.O(b,"mdxautoplaycancel",this.YI);this.T=this.o.O(b,"onVolumeChange",this.UC);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.hD,this);c.subscribe("remotePlayerChange",this.xm,this);c.subscribe("remoteQueueChange",this.Dp,this);c.subscribe("autoplayUpNext",this.FC,
this);c.subscribe("previousNextChange",this.eD,this);c.subscribe("nowAutoplaying",this.WC,this);c.subscribe("autoplayDismissed",this.EC,this);this.suggestion=null;this.H=new g.tP(64);this.A=new g.Wt(this.ME,500,this);g.N(this,this.A);this.B=new g.Wt(this.NE,1E3,this);g.N(this,this.B);this.J=new h7(this.pW,0,this);g.N(this,this.J);this.C={};this.K=new g.Wt(this.mF,1E3,this);g.N(this,this.K);this.I=new g.Rk(this.IO,1E3,this);g.N(this,this.I);this.M=g.y;this.QE();this.Dp();this.xm()},j9=function(a,b){var c=
a.F,d=a.l.getVideoData().lengthSeconds;
c.H=b||0;c.g.R("progresssync",b,d)},rDa=function(a){j9(a,0);
a.A.stop();k9(a,new g.tP(64))},m9=function(a,b){if(l9(a)&&!a.D){var c=null;
b&&(c={style:a.l.Ji()},g.cc(c,b));a.g.AE(a.l.getVideoData(1).videoId,c);a.C=E8(a.g).l}},n9=function(a,b){var c=a.l.eg();
if(c){var d=c.ie();var e=c.listId.toString()}var f=a.l.getVideoData(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;var m=f.Tj;f=bBa(f);var n=E8(c);l=l||0;var p={videoId:k,currentIndex:l};A8(n,k,l);g.t(b)&&(y8(n,b),p.currentTime=b);g.t(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.xg(f));I8(c,"setPlaylist",p);e||G8(c,n);k9(a,new g.tP(1))},sDa=function(a,b){if(b){var c=a.l.xc("captions","tracklist",{jA:1});
c&&c.length?(a.l.Kd("captions","track",b),a.D=!1):(a.l.ik("captions"),a.D=!0)}else a.l.Kd("captions","track",{})},l9=function(a){return E8(a.g).videoId==a.l.getVideoData(1).videoId},k9=function(a,b){a.B.stop();
var c=a.H;if(!g.yP(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.YU(a.l,d);a.H=b;tDa(a.F,c,b)}},o9=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",N:[{G:"div",L:"ytp-remote-display-status",N:[{G:"div",L:"ytp-remote-display-status-icon",N:[g.Xoa()]},{G:"div",L:"ytp-remote-display-status-text",aa:"{{statustext}}"}]}]});this.l=new g.NV(this,250);g.N(this,this.l);this.A=a;this.O(a,"presentingplayerstatechange",this.B);uDa(this,g.VU(a))},uDa=function(a,b){if(3==a.A.Pa()){var c={RECEIVER_NAME:a.A.xc("remote","currentReceiver").name};
c=g.X(b,128)?g.O0("Erro em $RECEIVER_NAME",c):b.kb()||g.X(b,4)?g.O0("Reproduzindo em $RECEIVER_NAME",c):g.O0("Conectado a $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},p9=function(a,b){g.WZ.call(this,"Reproduzir em",0,a,b);
this.l=a;this.H={};this.O(a,"onMdxReceiversChange",this.J);this.O(a,"presentingplayerstatechange",this.J);this.J()},q9=function(a){g.tV.call(this,a);
this.o={key:T6(),name:"Este computador"};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.tP(64);this.H=0;if(!g.QM(g.Y(this.g))){a=this.g;var b=g.CH(a);b&&(b=b.Yo())&&(b=new p9(a,b),g.N(this,b));b=new o9(a);g.N(this,b);g.nV(a,b.element,4)}},tDa=function(a,b,c){a.D=c;
a.g.R("presentingplayerstatechange",new g.DP(c,b))},r9=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)d9();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.getVideoData(1);var e=d.videoId;if(c||e){var f=a.g.eg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Yb(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Tj,index:Math.max(a.g.lB(),0),currentTime:0==f?void 0:f};(d=bBa(d))&&(c.locationInfo=d);d=c}else d=null;W8("Connecting to: "+g.xg(b));"cast-selector-receiver"==b.key?(Y8(d||null),s8()?p8().setLaunchParams(d||null):
n8("setLaunchParams called before ready.")):!d&&g9()&&V8()==b.key?g.VF("yt-remote-connection-change",!0):(d9(),Y8(d||null),d=U8().ke(),(d=V6(d,b.key))&&e9(d,1))}},JBa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},r7={"'":"\\'"},vDa={},hBa={dY:"atp",E2:"ska",S1:"que",c1:"mus",A2:"sus",l_:"dsp"};
O6.prototype.Rn=function(){var a=new O6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var a7,X6="",e7=b7("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",BBa=b7("loadCastFramework")||b7("loadCastApplicationFramework"),LCa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(h7,g.M);g.h=h7.prototype;g.h.LJ=function(a){this.A=arguments;this.g=!1;this.Ba?this.o=(0,g.F)()+this.pd:this.Ba=g.rg(this.B,this.pd)};
g.h.stop=function(){this.Ba&&(g.sg(this.Ba),this.Ba=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();h7.ba.V.call(this)};
g.h.MJ=function(){this.o?(this.Ba=g.rg(this.B,this.o-(0,g.F)()),this.o=null):(this.Ba=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};i7.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
i7.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=j7.prototype;g.h.mi=null;g.h.Gf=!1;g.h.Pk=null;g.h.kw=null;g.h.zk=null;g.h.Kj=null;g.h.mh=null;g.h.Jh=null;g.h.Ri=null;g.h.Qc=null;g.h.Sm=0;g.h.Hf=null;g.h.Dq=null;g.h.nh=null;g.h.Fl=-1;g.h.fE=!0;g.h.Wh=!1;g.h.Gs=0;g.h.Pp=null;var HBa={},m7={};g.h=j7.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.iV=function(a){a=a.target;var b=this.Pp;b&&3==g.gx(a)?b.Ij():this.wF(a)};
g.h.wF=function(a){try{if(a==this.Qc)a:{var b=g.gx(this.Qc),c=this.Qc.l,d=this.Qc.getStatus();if(g.wd&&!g.pc(10)||g.yd&&!g.oc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.cf&&!g.kx(this.Qc))break a;this.Wh||4!=b||7==c||(8==c||0>=d?this.g.Af(3):this.g.Af(2));t7(this);var e=this.Qc.getStatus();this.Fl=e;var f=g.kx(this.Qc);(this.Gf=200==e)?(4==b&&p7(this),this.B?(IBa(this,b,f),g.cf&&this.Gf&&3==b&&(this.W.U(this.l,"tick",this.eV),this.l.start())):o7(this,f),this.Gf&&!this.Wh&&(4==b?this.g.Bp(this):
(this.Gf=!1,l7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.nh=3,n7(13)):(this.nh=0,n7(14)),p7(this),q7(this))}}catch(k){this.Qc&&g.kx(this.Qc)}finally{}};
g.h.eV=function(){var a=g.gx(this.Qc),b=g.kx(this.Qc);this.Sm<b.length&&(t7(this),IBa(this,a,b),this.Gf&&4!=a&&l7(this))};
g.h.rU=function(a){s7((0,g.z)(this.qU,this,a),0)};
g.h.qU=function(a){this.Wh||(t7(this),o7(this,a),l7(this))};
g.h.pD=function(a){s7((0,g.z)(this.pU,this,a),0)};
g.h.pU=function(a){this.Wh||(p7(this),this.Gf=a,this.g.Bp(this),this.g.Af(4))};
g.h.cancel=function(){this.Wh=!0;p7(this)};
g.h.HU=function(){this.Pk=null;var a=(0,g.F)();0<=a-this.kw?(2!=this.Kj&&this.g.Af(3),p7(this),this.nh=2,n7(18),q7(this)):LBa(this,this.kw-a)};g.h=OBa.prototype;g.h.Es=null;g.h.te=null;g.h.Qp=!1;g.h.zz=null;g.h.fo=null;g.h.Mt=null;g.h.Fs=null;g.h.Me=null;g.h.Dg=-1;g.h.El=null;g.h.Zk=null;g.h.connect=function(a){this.Fs=a;a=v7(this.g,null,this.Fs);n7(3);this.zz=(0,g.F)();var b=this.g.F;null!=b?(this.El=b[0],(this.Zk=b[1])?(this.Me=1,PBa(this)):(this.Me=2,x7(this))):(N6(a,"MODE","init"),this.te=new j7(this,void 0,void 0,void 0),this.te.mi=this.Es,k7(this.te,a,!1,null,!0),this.Me=0)};
g.h.ZI=function(a){if(a)this.Me=2,x7(this);else{n7(4);var b=this.g;b.Uf=b.ah.Dg;E7(b,9)}a&&this.Af(2)};
g.h.Rr=function(a){return this.g.Rr(a)};
g.h.abort=function(){this.te&&(this.te.cancel(),this.te=null);this.Dg=-1};
g.h.yz=function(){return!1};
g.h.iD=function(a,b){this.Dg=a.Fl;if(0==this.Me)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Uf=this.Dg;E7(c,2);return}this.El=c[0];this.Zk=c[1]}else c=this.g,c.Uf=this.Dg,E7(c,2);else if(2==this.Me)if(this.Qp)n7(7),this.Mt=(0,g.F)();else if("11111"==b){if(n7(6),this.Qp=!0,this.fo=(0,g.F)(),c=this.fo-this.zz,!g.wd||g.pc(10)||500>c)this.Dg=200,this.te.cancel(),n7(12),w7(this.g,this,!0)}else n7(8),this.fo=this.Mt=(0,g.F)(),this.Qp=!1};
g.h.Bp=function(){this.Dg=this.te.Fl;if(this.te.Gf)0==this.Me?this.Zk?(this.Me=1,PBa(this)):(this.Me=2,x7(this)):2==this.Me&&((!g.wd||g.pc(10)?!this.Qp:200>this.Mt-this.fo)?(n7(11),w7(this.g,this,!1)):(n7(12),w7(this.g,this,!0)));else{0==this.Me?n7(9):2==this.Me&&n7(10);var a=this.g;a.Uf=this.Dg;E7(a,2)}};
g.h.Im=function(){return this.g.Im()};
g.h.isActive=function(){return this.g.isActive()};
g.h.Af=function(a){this.g.Af(a)};g.h=y7.prototype;g.h.ql=null;g.h.Wd=null;g.h.tc=null;g.h.Ds=null;g.h.lo=null;g.h.Lx=null;g.h.yo=null;g.h.pm=0;g.h.bQ=0;g.h.od=null;g.h.eh=null;g.h.sg=null;g.h.bi=null;g.h.ah=null;g.h.Cq=null;g.h.Yj=-1;g.h.zA=-1;g.h.Uf=-1;g.h.zj=0;g.h.mj=0;g.h.Yh=8;var F7=new g.Cf;g.A(RBa,g.af);g.A(SBa,g.af);g.A(TBa,g.af);g.h=y7.prototype;g.h.connect=function(a,b,c,d,e){n7(0);this.Ds=b;this.ql=c||{};d&&g.t(e)&&(this.ql.OSID=d,this.ql.OAID=e);this.C?(s7((0,g.z)(this.iy,this,a),100),XBa(this)):this.iy(a)};
g.h.iy=function(a){this.ah=new OBa(this);this.ah.Es=null;this.ah.l=this.B;this.ah.connect(a)};
g.h.yz=function(){return 0==this.g};
g.h.nD=function(a){this.eh=null;$Ba(this,a)};
g.h.mD=function(){this.sg=null;this.tc=new j7(this,this.o,"rpc",this.D);this.tc.mi=null;this.tc.Gs=0;var a=this.Lx.clone();g.Bm(a,"RID","rpc");g.Bm(a,"SID",this.o);g.Bm(a,"CI",this.Cq?"0":"1");g.Bm(a,"AID",this.Yj);z7(this,a);if(!g.wd||g.pc(10))g.Bm(a,"TYPE","xmlhttp"),k7(this.tc,a,!0,this.yo,!1);else{g.Bm(a,"TYPE","html");var b=this.tc,c=!!this.yo;b.Kj=3;b.mh=M6(a.clone());KBa(b,c)}};
g.h.iD=function(a,b){if(0!=this.g&&(this.tc==a||this.Wd==a))if(this.Uf=a.Fl,this.Wd==a&&3==this.g)if(7<this.Yh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.sg){if(this.tc)if(this.tc.zk+3E3<this.Wd.zk)B7(this),this.tc.cancel(),this.tc=null;else break a;D7(this);n7(19)}}else this.zA=c[1],0<this.zA-this.Yj&&37500>c[2]&&this.Cq&&0==this.mj&&!this.bi&&(this.bi=s7((0,g.z)(this.EQ,this),6E3));else E7(this,11)}else b!=vDa.gZ.g&&E7(this,11);else if(this.tc==a&&
B7(this),!g.C(b)){c=this.B.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.Yj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.yo=e[2],e=e[3],null!=e?this.Yh=e:this.Yh=6,this.g=3,this.od&&this.od.Xx(),this.Lx=v7(this,this.Im()?this.yo:null,this.Ds),aCa(this)):"stop"==e[0]&&E7(this,7):3==this.g&&("stop"==e[0]?E7(this,7):"noop"!=e[0]&&this.od&&this.od.Wx(e),this.mj=0)}}};
g.h.EQ=function(){null!=this.bi&&(this.bi=null,this.tc.cancel(),this.tc=null,D7(this),n7(20))};
g.h.Bp=function(a){if(this.tc==a){B7(this);this.tc=null;var b=2}else if(this.Wd==a)this.Wd=null,b=1;else return;this.Uf=a.Fl;if(0!=this.g)if(a.Gf)1==b?(b=(0,g.F)()-a.zk,F7.dispatchEvent(new SBa(F7,a.Ri?a.Ri.length:0,b,this.zj)),A7(this),this.A.length=0):aCa(this);else{var c=a.nh,d;if(!(d=3==c||7==c||0==c&&0<this.Uf)){if(d=1==b)this.Wd||this.eh||1==this.g||2<=this.zj?d=!1:(this.eh=s7((0,g.z)(this.nD,this,a),bCa(this,this.zj)),this.zj++,d=!0);d=!(d||2==b&&D7(this))}if(d)switch(c){case 1:E7(this,5);
break;case 4:E7(this,10);break;case 3:E7(this,6);break;case 7:E7(this,12);break;default:E7(this,2)}}};
g.h.uJ=function(a){if(!g.Oa(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.aW=function(a){a?n7(2):(n7(1),cCa(this,8))};
g.h.Rr=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.ax;a.F=!1;return a};
g.h.isActive=function(){return!!this.od&&this.od.isActive(this)};
g.h.Af=function(a){F7.dispatchEvent(new TBa(F7,a))};
g.h.Im=function(){return!(!g.wd||g.pc(10))};
g.h=dCa.prototype;g.h.Xx=function(){};
g.h.Wx=function(){};
g.h.Vx=function(){};
g.h.Er=function(){};
g.h.dz=function(){return{}};
g.h.isActive=function(){return!0};g.A(G7,g.M);g.h=G7.prototype;g.h.iU=function(){this.pd=Math.min(3E5,2*this.pd);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.pd+15E3*Math.random();g.Xt(this.g,a);this.l=(0,g.F)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.pd=5E3};g.A(H7,dCa);g.h=H7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Pd=function(a){return this.o.Pd(a)};
g.h.R=function(a,b){return this.o.R.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.Ze(this.o),gCa(this),g.Ze(this.l),this.l=null)};
g.h.ka=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new y7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.K),e=this.g;e&&(e.od=null);d.od=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Yj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.cc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):I7(this)&&YBa(this.g,c)};
g.h.Xx=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)YBa(this.g,a[b])}this.R("handlerOpened")};
g.h.Vx=function(a){var b=2==a&&401==this.g.Uf;4==a||b||this.l.start();this.R("handlerError",a)};
g.h.Er=function(a){if(!this.l.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.dz=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.cc(a,this.B);return a};
g.h.Wx=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),WBa(this.g)):this.R("handlerMessage",new eCa(a[0],a[1]))};
g.h.JW=function(){this.l.isActive();var a=this.g,b=0;a.tc&&b++;a.Wd&&b++;0!=b||this.connect(this.B,this.A)};J7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
J7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
J7.prototype.B=function(a){a(Error("request timed out"))};var oCa=(0,g.F)(),M7=null,P7=Array(50),O7=-1,Q7=!1;g.A(R7,g.FF);R7.prototype.ke=function(){return this.g};
R7.prototype.contains=function(a){return!!U6(this.g,a)};
R7.prototype.get=function(a){return a?V6(this.g,a):null};
R7.prototype.info=function(a){N7(this.D,a)};g.A(S7,g.FF);var wDa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=S7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Ba)&&this.BF()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Ba)||(g.WD(this.Ba),this.Ba=window.NaN)};
g.h.V=function(){this.stop();S7.ba.V.call(this)};
g.h.BF=function(){this.Ba=window.NaN;this.g=g.kE(K7(this.C,"/pairing/get_screen"),{method:"POST",Mb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.z)(this.LW,this),onError:(0,g.z)(this.KW,this),ud:(0,g.z)(this.MW,this)})};
g.h.LW=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.R("pairingComplete",new P6(c))};
g.h.KW=function(a){this.g=null;a.status&&404==a.status?this.l>=wDa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=wDa[this.l],this.Ba=g.UD((0,g.z)(this.BF,this),a),this.l++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.MW=function(){this.g=null;this.R("pairingFailed",Error("Server not responding"))};g.A(U7,R7);g.h=U7.prototype;g.h.start=function(){T7(this)&&this.R("screenChange");!g.MG("yt-remote-lounge-token-expiration")&&sCa(this);g.WD(this.l);this.l=g.UD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){T7(this);pCa(this,a);V7(this,!1);this.R("screenChange");b(a);a.token||sCa(this)};
g.h.remove=function(a,b){var c=T7(this);rCa(this,a)&&(V7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.xq=function(a,b,c,d){var e=T7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,V7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.V=function(){g.WD(this.l);U7.ba.V.call(this)};
g.h.ZJ=function(a){T7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}V7(this,!b);b&&N7(this.D,"Missed "+b+" lounge tokens.")};
g.h.YJ=function(a){N7(this.D,"Requesting lounge tokens failed: "+a)};g.A(X7,g.FF);g.h=X7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.MG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.F)()-144E5<a?0:a)?Z7(this):(this.A=(0,g.F)()+3E5,g.LG("yt-remote-fast-check-period",this.A),this.Av())};
g.h.isEmpty=function(){return g.Vb(this.g)};
g.h.update=function(){W7("Updating availability on schedule.");var a=this.C(),b=g.Jb(this.g,function(b,d){return b&&!!V6(a,d)},this);
Y7(this,b)};
g.h.V=function(){g.WD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);X7.ba.V.call(this)};
g.h.Av=function(){g.WD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=vCa(this);if(g.Mb(a)){var b=K7(this.B,"/pairing/get_screen_availability");this.l=L7(this.B,b,{lounge_token:g.Pb(a).join(",")},(0,g.z)(this.NT,this,a),(0,g.z)(this.LT,this))}else Y7(this,{}),Z7(this)};
g.h.NT=function(a,b){this.l=null;var c=g.Pb(vCa(this));if(g.gb(c,g.Pb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;Y7(this,d);Z7(this)}else this.fc("Changing Screen set during request."),this.Av()};
g.h.LT=function(a){this.fc("Screen availability failed: "+a);this.l=null;Z7(this)};
g.h.fc=function(a){N7("OnlineScreenService",a)};g.A($7,R7);g.h=$7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.R("screenChange"),this.l.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.xq=function(a,b,c,d){this.o.contains(a)?this.o.xq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,N7(this.D,a),d(Error(a)))};
g.h.ke=function(a){return a?this.g:g.Va(this.g,(0,g.Jd)(this.A,function(a){return!this.contains(a)},this))};
g.h.CF=function(){return(0,g.Jd)(this.ke(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.DF=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new S7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.Ze(f);d(a8(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Ze(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.OW=function(a,b,c,d){g.kE(K7(this.C,"/pairing/get_screen"),{method:"POST",Mb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(a,d){var e=new P6(d.screen||{});if(!e.name||zCa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);zCa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(a8(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
ud:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.Ze(this.o);g.Ze(this.l);$7.ba.V.call(this)};
g.h.oK=function(){ACa(this);this.R("screenChange");this.l.update()};
$7.prototype.dispose=$7.prototype.dispose;g.A(c8,g.FF);g.h=c8.prototype;g.h.Cp=function(a){this.o=a;this.R("sessionScreen",this.o)};
g.h.re=function(a){this.ka()||(a&&d8(this,""+a),this.o=null,this.R("sessionScreen",null))};
g.h.info=function(a){N7(this.K,a)};
g.h.FF=function(){return null};
g.h.Gv=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){d8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.Gv("");c8.ba.V.call(this)};g.A(e8,c8);g.h=e8.prototype;g.h.Fv=function(a){if(this.g){if(this.g==a)return;d8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);CCa(this)};
g.h.ak=function(a){this.info("launchWithParams no-op for Cast: "+g.xg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.re()},this),(0,g.z)(function(){this.re(Error("Failed to stop receiver app."))},this)):this.re(Error("Stopping cast device witout session."))};
g.h.Gv=g.y;g.h.V=function(){this.info("disposeInternal");g.WD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;e8.ba.V.call(this)};
g.h.TU=function(a,b){if(!this.ka())if(b){var c=g.Vw(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.xg(c));switch(d){case "mdxSessionStatus":BCa(this,c.screenId);break;default:d8(this,"Unknown youtube message: "+d)}}else d8(this,"Unable to parse message.")}else d8(this,"No data in message.")};
g.h.nz=function(a,b,c,d){yCa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(d8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.UD((0,g.z)(this.nz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.FF=function(){return this.g};
g.h.PW=function(a){this.ka()||a||(d8(this,"Cast session died."),this.re())};g.A(f8,c8);g.h=f8.prototype;g.h.Fv=function(a){this.A=a;this.A.addUpdateListener(this.J)};
g.h.ak=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.WD(this.C);this.A?this.A.stop((0,g.z)(this.re,this,null),(0,g.z)(this.re,this,"Failed to stop DIAL device.")):this.re()};
g.h.V=function(){this.g();this.g=g.y;g.WD(this.C);this.A&&this.A.removeUpdateListener(this.J);this.A=null;f8.ba.V.call(this)};
g.h.SW=function(a){this.ka()||a||(d8(this,"DIAL session died."),this.g(),this.g=g.y,this.re())};
g.h.zt=function(a){this.I=T6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,ECa(this));a(b);DCa(this)}else this.D=(0,g.z)(function(){g.WD(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,ECa(this));a(b);DCa(this)},this),this.C=g.UD((0,g.z)(function(){this.D()},this),100)};
g.h.CL=function(a,b,c){yCa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Cp(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.zt(b,c)},this),(0,g.z)(function(a){d8(this,"Failed to get DIAL screen: "+a);
this.zt(b,c)},this))};g.A(g8,c8);g8.prototype.stop=function(){this.re()};
g8.prototype.Fv=g.y;g8.prototype.ak=function(){g.WD(this.g);this.g=window.NaN;var a=V6(this.H.ke(),this.l.label);a?this.Cp(a):this.re(Error("No such screen"))};
g8.prototype.V=function(){g.WD(this.g);this.g=window.NaN;g8.ba.V.call(this)};g.A(h8,g.FF);g.h=h8.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.jD,this),(0,g.z)(this.vT,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.oR,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ka()||(window.chrome.cast.addReceiverActionListener(this.A),lCa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.EF,this)),this.o=GCa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.fc("Failed to set initial custom receivers: "+g.xg(a))},this)),this.R("yt-remote-cast2-availability-change",j8(this)),b(!0))},this),(0,g.z)(function(a){this.fc("Failed to initialize API: "+g.xg(a));
b(!1)},this))};
g.h.KV=function(a,b){i8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)i8("Unsetting old screen status: "+this.g.l.friendlyName),k8(this,null)}if(a&&b){if(!this.g){c=V6(this.l.ke(),a);if(!c){i8("setConnectedScreenStatus: Unknown screen.");return}var d=FCa(this,c);d||(i8("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.fc("Failed to set initial custom receivers: "+g.xg(a))},this)));
i8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);k8(this,new g8(this.l,d),!0)}this.g.Gv(b)}else i8("setConnectedScreenStatus: no screen.")};
g.h.LV=function(a){this.ka()?this.fc("Setting connection data on disposed cast v2"):this.g?this.g.ak(a):this.fc("Setting connection data without a session")};
g.h.RW=function(){this.ka()?this.fc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),k8(this,null)):i8("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.jD,this),(0,g.z)(this.ST,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.EF,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Ta(g.x("yt.mdx.remote.debug.handlers_")||[],iCa);g.Ze(this.g);h8.ba.V.call(this)};
g.h.fc=function(a){N7("Controller",a)};
g.h.kD=function(a,b){this.g==a&&(b||k8(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.rT=function(a,b){if(!this.ka())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),i8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)i8("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{i8("onReceiverAction_: Casting to active receiver.");this.g.o&&this.R("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:k8(this,
new g8(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:k8(this,new f8(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:k8(this,new e8(this.l,a));break;default:this.fc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.fc("Stopping receiver w/o session: "+a.friendlyName)}else this.fc("onReceiverAction_ called without receiver.")};
g.h.oR=function(a){if(this.ka())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.fc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.fc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return i8("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.fc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);k8(this,new f8(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.CL,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.zt,b))};
g.h.jD=function(a){if(!this.ka()){i8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)i8("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),k8(this,new e8(this.l,b),!0);else{this.fc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=V6(this.l.ke(),c.label);
d&&Q6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(i8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ze(this.g),this.g=new e8(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.kD,this,this.g)),this.g.ak(null));this.g.Fv(a)}}};
g.h.QW=function(){return this.g?this.g.FF():null};
g.h.ST=function(a){this.ka()||(this.fc("Failed to estabilish a session: "+g.xg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&k8(this,null))};
g.h.vT=function(a){i8("Receiver availability updated: "+a);if(!this.ka()){var b=j8(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;j8(this)!=b&&this.R("yt-remote-cast2-availability-change",j8(this))}};
g.h.EF=function(){this.ka()||(this.o=GCa(this),i8("Updating custom receivers: "+g.xg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.fc("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",j8(this)))};
h8.prototype.setLaunchParams=h8.prototype.LV;h8.prototype.setConnectedScreenStatus=h8.prototype.KV;h8.prototype.stopSession=h8.prototype.RW;h8.prototype.getCastSession=h8.prototype.QW;h8.prototype.requestSession=h8.prototype.requestSession;h8.prototype.init=h8.prototype.init;h8.prototype.dispose=h8.prototype.dispose;var q8=[];g.h=v8.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";w8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Xf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.kb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+x8(this):this.H};
g.h.clone=function(){return new v8(B8(this))};g.A(D8,g.FF);g.h=D8.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,J8(this,"play")):I8(this,"play"),H8(this,1,z8(E8(this))),this.R("remotePlayerChange")):F8(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,J8(this,"pause")):I8(this,"pause"),H8(this,2,z8(E8(this))),this.R("remotePlayerChange")):F8(this,this.pause)};
g.h.AF=function(a){if(1==this.g){if(this.l){var b=E8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,J8(this,"seekTo",{newTime:a}))}else I8(this,"seekTo",{newTime:a});H8(this,3,a);this.R("remotePlayerChange")}else F8(this,g.Fa(this.AF,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,J8(this,"stopVideo")):I8(this,"stopVideo");var a=E8(this);a.index=-1;a.videoId="";w8(a);G8(this,a);this.R("remotePlayerChange")}else F8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=E8(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){N7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.fc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){N7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.fc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);I8(this,"setVolume",e)}c.muted=b;c.volume=a;G8(this,c)}else F8(this,g.Fa(this.setVolume,a,b))};
g.h.AE=function(a,b){if(1==this.g){var c=E8(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.xg(b.style),g.cc(d,c.l));I8(this,"setSubtitlesTrack",d);G8(this,c)}else F8(this,g.Fa(this.AE,a,b))};
g.h.rw=function(a,b){if(1==this.g){I8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Fb.id});var c=E8(this);c.audioTrackId=b.Fb.id;G8(this,c)}else F8(this,g.Fa(this.rw,a,b))};
g.h.zF=function(a,b){if(1==this.g){if(a&&b){var c=E8(this);A8(c,a,b);G8(this,c)}I8(this,"previous")}else F8(this,g.Fa(this.zF,a,b))};
g.h.yF=function(a,b){if(1==this.g){if(a&&b){var c=E8(this);A8(c,a,b);G8(this,c)}I8(this,"next")}else F8(this,g.Fa(this.yF,a,b))};
g.h.Ey=function(){1==this.g?I8(this,"dismissAutoplay"):F8(this,this.Ey)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.R("proxyStateChange",a,this.g)}D8.ba.dispose.call(this)};
g.h.V=function(){TCa(this);this.A=null;this.B.clear();C8(this,null);D8.ba.V.call(this)};
g.h.tw=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.nC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.mT=function(a,b){this.R(a,b)};
g.h.LQ=function(a){if(!a)this.sm(null),C8(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=E8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)N7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,G8(this,b)}};
g.h.sm=function(a){N7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),UCa(this),this.R("remotePlayerChange")};
g.h.KQ=function(a){a?(UCa(this),this.R("remotePlayerChange")):this.sm(null)};
g.h.XQ=function(){var a=QCa();a&&C8(this,a)};
g.h.fc=function(a){N7("CP",a)};g.A(K8,g.FF);g.h=K8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Za.listId=c);this.Za.videoId=d;this.Za.index=k||0;this.Za.state=3;y8(this.Za,m);this.A="UNSUPPORTED";L8("Connecting with setPlaylist and params: "+g.xg(l));this.g.connect({method:"setPlaylist",
params:g.xg(l)},a,pBa())}else L8("Connecting without params"),this.g.connect({},a,pBa());WCa(this)};
g.h.dispose=function(){this.ka()||(this.R("beforeDispose"),M8(this,3));K8.ba.dispose.call(this)};
g.h.V=function(){N8(this);P8(this);O8(this);g.WD(this.H);this.H=window.NaN;g.WD(this.I);this.I=window.NaN;this.o=null;g.pF(this.T);this.T.length=0;this.g.dispose();K8.ba.V.call(this);this.A=this.D=this.l=this.Za=this.g=null};
g.h.QJ=function(){this.C(2)};
g.h.PQ=function(){L8("Channel opened");this.M&&(this.M=!1,O8(this),this.K=g.UD((0,g.z)(function(){L8("Timing out waiting for a screen.");this.C(1)},this),15E3));
tBa(fCa(this.g),this.Z)};
g.h.MQ=function(){L8("Channel closed");(0,window.isNaN)(this.B)?$6(!0):$6();this.dispose()};
g.h.NQ=function(a){$6();(0,window.isNaN)(this.F())?(L8("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,L8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),M8(this,2))};
g.h.OQ=function(a){a.params?L8("Received: action="+a.action+", params="+g.xg(a.params)):L8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Vw(a.params.devices);this.l=(0,g.G)(a,function(a){return new O6(a)});
a=!!g.Ka(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
ZCa(this,a);break;case "loungeScreenDisconnected":g.Ua(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
ZCa(this,!1);break;case "remoteConnected":var b=new O6(g.Vw(a.params.device));g.Ka(this.l,function(a){return b?a.id==b.id:!1})||g.Ra(this.l,b);
break;case "remoteDisconnected":b=new O6(g.Vw(a.params.device));g.Ua(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":aDa(this,a);break;case "nowPlaying":cDa(this,a);break;case "onStateChange":bDa(this,a);break;case "onAdStateChange":dDa(this,a);break;case "onVolumeChanged":eDa(this,a);break;case "onSubtitlesTrackChanged":$Ca(this,a);break;case "nowAutoplaying":fDa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.R("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":gDa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:L8("Unrecognized action: "+a.action)}};
g.h.tV=function(){if(this.o){var a=this.o;this.o=null;this.Za.videoId!=a&&Q8(this,"getNowPlaying")}};
K8.prototype.subscribe=K8.prototype.subscribe;K8.prototype.unsubscribeByKey=K8.prototype.Pd;K8.prototype.ga=function(){var a=3;this.ka()||(a=0,(0,window.isNaN)(this.F())?I7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
K8.prototype.getProxyState=K8.prototype.ga;K8.prototype.C=function(a){L8("Disconnecting with "+a);N8(this);this.R("beforeDisconnect",a);1==a&&$6();gCa(this.g,a);this.dispose()};
K8.prototype.disconnect=K8.prototype.C;K8.prototype.fa=function(){var a=this.Za;this.o&&(a=this.Za.clone(),A8(a,this.o,a.index));return B8(a)};
K8.prototype.getPlayerContextData=K8.prototype.fa;
K8.prototype.na=function(a){var b=new v8(a);b.videoId&&b.videoId!=this.Za.videoId&&(this.o=b.videoId,g.WD(this.H),this.H=g.UD((0,g.z)(this.tV,this),5E3));var c=[];this.Za.listId==b.listId&&this.Za.videoId==b.videoId&&this.Za.index==b.index||c.push("remoteQueueChange");this.Za.g==b.g&&this.Za.volume==b.volume&&this.Za.muted==b.muted&&z8(this.Za)==z8(b)&&g.xg(this.Za.l)==g.xg(b.l)||c.push("remotePlayerChange");this.Za.reset(a);(0,g.B)(c,function(a){this.R(a)},this)};
K8.prototype.setPlayerContextData=K8.prototype.na;K8.prototype.X=function(){var a=this.g.C.id,b=g.Ka(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
K8.prototype.getOtherConnectedRemoteId=K8.prototype.X;K8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.F)():window.NaN};
K8.prototype.getReconnectTimeout=K8.prototype.F;K8.prototype.Y=function(){return this.A||"UNSUPPORTED"};
K8.prototype.getAutoplayMode=K8.prototype.Y;K8.prototype.da=function(){return this.D||""};
K8.prototype.getAutoplayVideoId=K8.prototype.da;K8.prototype.sa=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.Yt(a.g);a.start()}};
K8.prototype.reconnect=K8.prototype.sa;K8.prototype.ha=function(a,b){Q8(this,a,b);YCa(this)};
K8.prototype.sendMessage=K8.prototype.ha;g.A(R8,R7);g.h=R8.prototype;g.h.ke=function(a){return this.ed.$_gs(a)};
g.h.contains=function(a){return!!this.ed.$_c(a)};
g.h.get=function(a){return this.ed.$_g(a)};
g.h.start=function(){this.ed.$_st()};
g.h.add=function(a,b,c){this.ed.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.ed.$_r(a,b,c)};
g.h.xq=function(a,b,c,d){this.ed.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.ed.$_ubk(this.l[a]);this.l.length=0;this.ed=null;R8.ba.V.call(this)};
g.h.NW=function(){this.R("screenChange")};
g.h.NS=function(){this.R("onlineScreenChange")};
$7.prototype.$_st=$7.prototype.start;$7.prototype.$_gspc=$7.prototype.OW;$7.prototype.$_gsppc=$7.prototype.DF;$7.prototype.$_c=$7.prototype.contains;$7.prototype.$_g=$7.prototype.get;$7.prototype.$_a=$7.prototype.add;$7.prototype.$_un=$7.prototype.xq;$7.prototype.$_r=$7.prototype.remove;$7.prototype.$_gs=$7.prototype.ke;$7.prototype.$_gos=$7.prototype.CF;$7.prototype.$_s=$7.prototype.subscribe;$7.prototype.$_ubk=$7.prototype.Pd;var S8=null,T8=null,h9=null,X8=[];g.q(i9,g.M);g.h=i9.prototype;
g.h.V=function(){g.M.prototype.V.call(this);this.A.stop();this.B.stop();this.J.stop();this.M();this.g.unsubscribe("proxyStateChange",this.hD,this);this.g.unsubscribe("remotePlayerChange",this.xm,this);this.g.unsubscribe("remoteQueueChange",this.Dp,this);this.g.unsubscribe("autoplayUpNext",this.FC,this);this.g.unsubscribe("previousNextChange",this.eD,this);this.g.unsubscribe("nowAutoplaying",this.WC,this);this.g.unsubscribe("autoplayDismissed",this.EC,this);this.g=this.F=null};
g.h.FB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(l9(this)){if(!E8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":E8(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.Ij(c[0],c[1]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.rw(this.l.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();n9(this,0==c?void 0:c);break;case "control_seek":n9(this,c[0]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.rw(this.l.getVideoData(1).videoId,c)}};
g.h.JQ=function(a){this.J.LJ(a)};
g.h.pW=function(a){this.FB("control_subtitles_set_track",g.Vb(a)?null:a)};
g.h.QE=function(){var a=this.l.xc("captions","track");g.Vb(a)||m9(this,a)};
g.h.UC=function(a){if(l9(this)){this.g.unsubscribe("remotePlayerChange",this.xm,this);var b=Math.round(a.volume);a=!!a.muted;var c=E8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.K.start();this.g.subscribe("remotePlayerChange",this.xm,this)}};
g.h.eS=function(){g.Vb(this.C)||sDa(this,this.C);this.D=!1};
g.h.hD=function(a,b){this.B.stop();2==b&&this.NE()};
g.h.xm=function(){if(l9(this)){this.A.stop();var a=E8(this.g);switch(a.g){case 1081:case 1:k9(this,new g.tP(8));this.ME();break;case 1085:case 3:k9(this,new g.tP(9));break;case 1083:case 0:k9(this,new g.tP(2));this.I.stop();j9(this,this.l.getVideoData().lengthSeconds);break;case 1084:k9(this,new g.tP(4));break;case 2:k9(this,new g.tP(4));j9(this,z8(a));break;case -1:k9(this,new g.tP(64));break;case -1E3:k9(this,new g.tP(128,{errorCode:"mdx.remoteerror",message:"Este v\u00eddeo n\u00e3o est\u00e1 dispon\u00edvel para reprodu\u00e7\u00e3o remota."}))}a=
E8(this.g).l;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,sDa(this,a));a=E8(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.K.isActive()||this.mF()}else rDa(this)};
g.h.eD=function(){this.l.R("mdxpreviousnextchange")};
g.h.Dp=function(){l9(this)||rDa(this)};
g.h.YI=function(){this.g.Ey()};
g.h.FC=function(a){a&&(a=g.kE("/watch_queue_ajax",{method:"GET",Zc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.z)(this.uU,this)}))&&(this.M=(0,g.z)(a.abort,a))};
g.h.uU=function(a,b){var c=new g.nO({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.R("mdxautoplayupnext",c)};
g.h.WC=function(a){(0,window.isNaN)(a)||this.l.R("mdxnowautoplaying",a)};
g.h.EC=function(){this.l.R("mdxautoplaycanceled")};
g.h.IO=function(a,b){-1==E8(this.g).g?n9(this,a):b&&this.g.AF(a)};
g.h.mF=function(){if(l9(this)){var a=E8(this.g);this.o.Ea(this.T);a.muted?this.l.mute():this.l.fg();this.l.setVolume(a.volume);this.T=this.o.O(this.l,"onVolumeChange",this.UC)}};
g.h.ME=function(){this.A.stop();if(!this.g.ka()){var a=E8(this.g);a.kb()&&k9(this,new g.tP(8));j9(this,z8(a));this.A.start()}};
g.h.NE=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.q(o9,g.W);o9.prototype.B=function(a){uDa(this,a.state)};g.q(p9,g.WZ);p9.prototype.J=function(){var a=this.l.xc("remote","receivers");a&&1<a.length&&!this.l.xc("remote","quickCast")?(this.H=g.jb(a,this.C,this),g.XZ(this,(0,g.G)(a,this.C)),a=this.l.xc("remote","currentReceiver"),this.zf(this.C(a)),this.enable(!0)):this.enable(!1)};
p9.prototype.C=function(a){return a.key};
p9.prototype.yf=function(a){return"cast-selector-receiver"==a?"Elenco...":this.H[a].name};
p9.prototype.sd=function(a){g.WZ.prototype.sd.call(this,a);this.l.Kd("remote","currentReceiver",this.H[a]);this.B.Qb()};g.q(q9,g.tV);g.h=q9.prototype;g.h.create=function(){lDa(g.DM(g.Y(this.g)));this.C.push(g.RF("yt-remote-before-disconnect",this.FQ,this));this.C.push(g.RF("yt-remote-connection-change",this.wT,this));this.C.push(g.RF("yt-remote-receiver-availability-change",this.fD,this));this.C.push(g.RF("yt-remote-auto-connect",this.uT,this));this.C.push(g.RF("yt-remote-receiver-resumed",this.tT,this));this.fD()};
g.h.load=function(){this.g.tu();g.tV.prototype.load.call(this);this.B=new i9(this,this.g,this.l);var a=(a=qDa())?a.currentTime:0;var b=g9()?new D8(b9(),void 0):null;0==a&&b&&(a=z8(E8(b)));0!=a&&(this.H=a||0,this.g.R("progresssync",a,void 0));tDa(this,this.D,this.D);g.s0(this.g.app,6)};
g.h.unload=function(){this.g.R("mdxautoplaycanceled");this.A=this.o;g.$e(this.B,this.l);this.l=this.B=null;g.tV.prototype.unload.call(this);g.s0(this.g.app,5)};
g.h.V=function(){g.SF(this.C);g.tV.prototype.V.call(this)};
g.h.im=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.FB.apply(this.B,[a].concat(g.pa(c)))};
g.h.HJ=function(){return this.loaded?this.B.suggestion:null};
g.h.Xf=function(){return this.l?E8(this.l).Xf:!1};
g.h.hasNext=function(){return this.l?E8(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.wO=function(){var a=E8(this.l),b=this.g.getVideoData();return{allowSeeking:this.g.fd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+x8(a):a.A,isPeggedToLive:1>=(a.C?a.o+x8(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+x8(a):a.o,seekableStart:0<a.B?a.B+x8(a):a.B}};
g.h.xO=function(){this.l&&this.l.yF()};
g.h.yO=function(){this.l&&this.l.zF()};
g.h.FQ=function(a){1==a&&(this.I=this.l?E8(this.l):null)};
g.h.wT=function(){var a=g9()?new D8(b9(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.Ze(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.getVideoData().videoId&&this.g.jB(a.videoId,z8(a)));this.g.R("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.fD=function(){this.F=[this.o].concat(nDa());var a=c9()||this.o;r9(this,a);this.g.va("onMdxReceiversChange")};
g.h.uT=function(){var a=c9();r9(this,a)};
g.h.tT=function(){this.A=c9()};
g.h.vO=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?t8():r9(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&t8(),!0):!1}};
g.h.zO=function(){I8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Hc=function(){return!1};g.jY.remote=q9;})(_yt_player);
