var OA_output = new Array(); 
OA_output['banner_a'] = '';
OA_output['banner_a'] += "<"+"div id=\"537197064_728_90_1\" style=\"width:728px;height:90px;margin:0;padding:0\">\n";
OA_output['banner_a'] += "<"+"noscript><"+"iframe id=\"312662a236\" name=\"312662a236\" src=\"//us-ads.openx.net/w/1.0/afr?auid=537197064&cb=b99209cf01\" frameborder=\"0\" scrolling=\"no\" width=\"728\" height=\"90\"><"+"a href=\"//us-ads.openx.net/w/1.0/rc?cs=312662a236&cb=b99209cf01\" ><"+"img src=\"//us-ads.openx.net/w/1.0/ai?auid=537197064&cs=312662a236&cb=b99209cf01\" border=\"0\" alt=\"\"><"+"/a><"+"/iframe><"+"/noscript>\n";
OA_output['banner_a'] += "<"+"/div>\n";
OA_output['banner_a'] += "<"+"script type=\"text/javascript\">\n";
OA_output['banner_a'] += "var OX_ads = OX_ads || [];\n";
OA_output['banner_a'] += "OX_ads.push({\n";
OA_output['banner_a'] += "slot_id: \"537197064_728_90_1\",\n";
OA_output['banner_a'] += "auid: \"537197064\"\n";
OA_output['banner_a'] += "});\n";
OA_output['banner_a'] += "<"+"/script>\n";
OA_output['banner_a'] += "<"+"script type=\"text/javascript\" src=\"//us-ads.openx.net/w/1.0/jstag\"><"+"/script><"+"div id=\'beacon_b99209cf01\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.clubedohardware.com.br/www/delivery/lg.php?bannerid=1429&amp;campaignid=548&amp;zoneid=167&amp;loc=https%3A%2F%2Fwww.clubedohardware.com.br%2Fforums%2Ftopic%2F149989-como-ver-os-codigos-fonte-de-programas-exe%2F&amp;cb=b99209cf01\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['banner_c1'] = '';
OA_output['banner_c1'] += "<"+"script type=\"text/javascript\" src=\"//static.criteo.net/js/ld/publishertag.js\"><"+"/script>\n";
OA_output['banner_c1'] += "<"+"script type=\"text/javascript\">\n";
OA_output['banner_c1'] += "Criteo.DisplayAd({\n";
OA_output['banner_c1'] += "\"zoneid\": 513323,\n";
OA_output['banner_c1'] += "\"async\": false});\n";
OA_output['banner_c1'] += "<"+"/script><"+"div id=\'beacon_dd827f6b56\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.clubedohardware.com.br/www/delivery/lg.php?bannerid=954&amp;campaignid=273&amp;zoneid=168&amp;loc=https%3A%2F%2Fwww.clubedohardware.com.br%2Fforums%2Ftopic%2F149989-como-ver-os-codigos-fonte-de-programas-exe%2F&amp;cb=dd827f6b56\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['banner_c2'] = '';
OA_output['banner_c2'] += "<"+"div id=\'beacon_96a8730e7f\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.clubedohardware.com.br/www/delivery/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=169&amp;loc=https%3A%2F%2Fwww.clubedohardware.com.br%2Fforums%2Ftopic%2F149989-como-ver-os-codigos-fonte-de-programas-exe%2F&amp;cb=96a8730e7f\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['banner_e1'] = '';
OA_output['banner_e1'] += "<"+"script type=\"text/javascript\" src=\"//static.criteo.net/js/ld/publishertag.js\"><"+"/script>\n";
OA_output['banner_e1'] += "<"+"script type=\"text/javascript\">\n";
OA_output['banner_e1'] += "Criteo.DisplayAd({\n";
OA_output['banner_e1'] += "\"zoneid\": 167083,\n";
OA_output['banner_e1'] += "\"async\": false});\n";
OA_output['banner_e1'] += "<"+"/script><"+"div id=\'beacon_be2093cae0\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.clubedohardware.com.br/www/delivery/lg.php?bannerid=1430&amp;campaignid=713&amp;zoneid=265&amp;loc=https%3A%2F%2Fwww.clubedohardware.com.br%2Fforums%2Ftopic%2F149989-como-ver-os-codigos-fonte-de-programas-exe%2F&amp;cb=be2093cae0\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['banner_e2'] = '';
OA_output['banner_e2'] += "<"+"script type=\"text/javascript\" src=\"//static.criteo.net/js/ld/publishertag.js\"><"+"/script>\n";
OA_output['banner_e2'] += "<"+"script type=\"text/javascript\">\n";
OA_output['banner_e2'] += "Criteo.DisplayAd({\n";
OA_output['banner_e2'] += "\"zoneid\": 1136237,\n";
OA_output['banner_e2'] += "\"async\": false});\n";
OA_output['banner_e2'] += "<"+"/script><"+"div id=\'beacon_60d782ee83\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.clubedohardware.com.br/www/delivery/lg.php?bannerid=1431&amp;campaignid=715&amp;zoneid=282&amp;loc=https%3A%2F%2Fwww.clubedohardware.com.br%2Fforums%2Ftopic%2F149989-como-ver-os-codigos-fonte-de-programas-exe%2F&amp;cb=60d782ee83\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['banner_e3'] = '';
OA_output['banner_e3'] += "<"+"div id=\'beacon_4d14687268\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.clubedohardware.com.br/www/delivery/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=249&amp;loc=https%3A%2F%2Fwww.clubedohardware.com.br%2Fforums%2Ftopic%2F149989-como-ver-os-codigos-fonte-de-programas-exe%2F&amp;cb=4d14687268\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['banner_e4'] = '';
OA_output['banner_e4'] += "<"+"div id=\"539228491_300_250_btf\" style=\"width:300px;height:250px;margin:0;padding:0\">\n";
OA_output['banner_e4'] += "<"+"noscript><"+"iframe id=\"3053590181\" name=\"3053590181\" src=\"//us-ads.openx.net/w/1.0/afr?auid=539228491&cb=4ee5f87e61\" frameborder=\"0\" scrolling=\"no\" width=\"300\" height=\"250\"><"+"a href=\"//us-ads.openx.net/w/1.0/rc?cs=3053590181&cb=4ee5f87e61\" ><"+"img src=\"//us-ads.openx.net/w/1.0/ai?auid=539228491&cs=3053590181&cb=4ee5f87e61\" border=\"0\" alt=\"\"><"+"/a><"+"/iframe><"+"/noscript>\n";
OA_output['banner_e4'] += "<"+"/div>\n";
OA_output['banner_e4'] += "<"+"script type=\"text/javascript\">\n";
OA_output['banner_e4'] += "var OX_ads = OX_ads || [];\n";
OA_output['banner_e4'] += "OX_ads.push({\n";
OA_output['banner_e4'] += "slot_id: \"539228491_300_250_btf\",\n";
OA_output['banner_e4'] += "auid: \"539228491\"\n";
OA_output['banner_e4'] += "});\n";
OA_output['banner_e4'] += "<"+"/script>\n";
OA_output['banner_e4'] += "<"+"script type=\"text/javascript\" src=\"//us-ads.openx.net/w/1.0/jstag\"><"+"/script><"+"div id=\'beacon_4ee5f87e61\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://ads.clubedohardware.com.br/www/delivery/lg.php?bannerid=3398&amp;campaignid=745&amp;zoneid=299&amp;loc=https%3A%2F%2Fwww.clubedohardware.com.br%2Fforums%2Ftopic%2F149989-como-ver-os-codigos-fonte-de-programas-exe%2F&amp;cb=4ee5f87e61\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
